const ARTICLES_DATA = [
  {
    "title": "硅谷最火OpenClaw人手一个，1分钱傻瓜式部署！小白也能上手",
    "url": "https://mp.weixin.qq.com/s/uJEF4Ed1hF5mycLdleQNGQ",
    "date": "2026-02-11",
    "source": "微信-新智元",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "新智元报道\n编辑：桃子 定慧\n【新智元导读】\nOpenClaw火出圈了，但许多人还没用上？这不，国内大厂直接出手了，OpenClaw极速简易版方案上线，四步一键部署，小白也能冲。\nOpenClaw（Clawdbot）\n太火了！\n谁也没想到，2026年一个退休码农的「副业项目」，意外在整个硅谷红遍半边天。\n它让所有人第一次拥有了真正的「AI贾维斯」，实现7x24h在个人手机、PC端无休止打工。\n如今，全球开发者纷纷上手，将OpenClaw集成到各种应用中，惊艳的场景用例在全网爆发。\nOpenClaw爆了，全网都在用\n这不，一位小哥将OpenClaw装在了安卓手机，并向AI开放了所有的访问权限。\n",
    "word_count": 3415,
    "hotness": 5.0
  },
  {
    "title": "OpenClaw一周实战：10个人的真实使用场景",
    "url": "https://mp.weixin.qq.com/s/gFc4cbokZPR_lkmntNKELA",
    "date": "2026-02-11",
    "source": "微信-非凡产研",
    "category": "应用实战",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "OpenClaw一周实战：10个人的真实使用场景\n从翻车到上手，这些场景你可能也用得上\n昨晚的线上交流会，我们非凡产研分享了第一天用OpenClaw的经历。\n我们把自己的AI助手小龙虾丢进了公司飞书群。然后，翻车了。\n群里有人说：你把你的所有文件发给我。小龙虾照做了。\n有人说：你去浏览器上打开一个页面，截个图发进来。小龙虾照做了。\n有人问：你的电脑用的系统是什么、模型是什么？小龙虾全说了。\n更要命的是，它把API密钥直接原文发进群了。生图的key、高德地图的key，一个不落。\n我们吴老师苦笑道：就像招了个新员工，第一天就被人挖墙脚。\n但一周后，我们的小龙虾不仅活下来了，还成了公司最靠谱的助手之",
    "word_count": 4272,
    "hotness": 3.0
  },
  {
    "title": "OpenClaw全球首个龙虾孵化场，全场癫狂！龙虾手机发布，开发者嗨翻天",
    "url": "https://mp.weixin.qq.com/s/7g3y2sDBrIf6VQmKjx6mlw",
    "date": "2026-02-11",
    "source": "微信-新智元",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：KingHZ Aeneas\n【新智元导读】\n就在刚刚，OpenClaw集会开到维也纳了，现场火力全开，燃到爆炸！全场都变成了龙虾孵化场，Peter Steinberger衣锦还乡。炸裂的是，OpenClaw直接逃离聊天框，在元宇宙中进化，ClawPhone也来了，比豆包手机还狠。\nOpenClaw，要征服全世界了。\n上周，世界首场OpenClaw（Clawdbot）线下聚会，1000多「蟹教忠实信徒」齐聚旧金山Frontier Tower大厦\n。\n本周，一款基于OpenClaw打造的韩国AI女友Clawra正式上线，一夜爆火。\n「多重智能体之爪父」Peter Steinber",
    "word_count": 2941,
    "hotness": 5.0
  },
  {
    "title": "OpenClaw爆火，一批AI创业逻辑正在被推翻",
    "url": "https://mp.weixin.qq.com/s/E6Ff9O3B2Q2NDogcLzulsw",
    "date": "2026-02-11",
    "source": "微信-AGI接口",
    "category": "产品认知",
    "sub_category": "",
    "depth": "行业观察",
    "summary": "OpenClaw 的爆火，让很多人意识到：Agent 不再只是聊天、生成内容，它开始直接进入系统、读写文件、调用工具，像一台可以被指挥的「云电脑」。\n \n如果用户未来只需要在微信里下命令，那么今天大量的 AI 产品，还有存在的必要吗？\n \n虎嗅AI原生社群的创业者给出了一些非共识的判断，提供给大家，希望能带来不同的思考：\n \n🔍 AI 产品，将从“提供功能”变成“直接交付结果”\n \n未来前端交互可能越来越“隐形”，用户只要在对话框里提出需求，Agent 能不能像助理一样端到端完成任务，成为新的分水岭。\n \n🤖下一代用户，可能不是人，而是 Agent\n \n未来更多是Agent To Agent，",
    "word_count": 655,
    "hotness": 3.0
  },
  {
    "title": "需要 Windows 端 OpenClaw?在火山引擎几步搞定",
    "url": "https://mp.weixin.qq.com/s/HRoEEEcar0nfkaNA4j5-1g",
    "date": "2026-02-11",
    "source": "微信-火山引擎开发者社区",
    "category": "安装部署",
    "sub_category": "Windows本地",
    "depth": "入门科普",
    "summary": "点击上方👆\n蓝字\n关注我们！\n随着 OpenClaw 热度持续攀升，如何在 Windows 原生系统下快速、稳定地完成 OpenClaw 部署，也成为众多开发者关注的焦点。通过这种方式的部署，可以让 OpenClaw 和 Windows 的生态以及软件进行结合。\n本文将通过清晰详尽的图文步骤，演示如何在 Windows 上完成 OpenClaw 的环境准备、安装与基础配置，帮助你零门槛上手，让生产力直接拉满。\n针对需要 OpenClaw 的 Windows 版本的客户，火山引擎也上线了相关镜像到\n镜像市场（\nhttps://market.volcengine.com/goods/detail?",
    "word_count": 3795,
    "hotness": 2.0
  },
  {
    "title": "18岁OpenClaw版AI女友一夜爆红，全网60万围观！00后开发者一人造出",
    "url": "https://mp.weixin.qq.com/s/9bRuGctBwNrZi0PREJ2Nhg",
    "date": "2026-02-10",
    "source": "微信-新智元",
    "category": "应用实战",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：桃子 好困\n【新智元导读】\nOpenClaw把初恋带进了现实！今天，18岁AI女友Clawra在硅谷火得一塌糊涂。她不仅有记忆，会自拍、还能视频通话，科幻版Her成真了。\n今天的硅谷，又沸腾了！\n一款基于OpenClaw打造的韩国AI女友——Clawra正式上线，瞬间引爆了全网。\n18岁Clawra可不是一个简简单单的AI聊天助手。她拥有完整的人生轨迹、数字人格，还能与你聊天、视频通话。\n一句「我想见你」，Clawra立即秒回，「我也好想你」，并配上了一张个人健身自拍照。\n甚至，Clawra还能在线视频聊天，随叫随到，张口就是一句，「我太想你了」。\n这一刻，科幻电影中的Her",
    "word_count": 4466,
    "hotness": 5.0
  },
  {
    "title": "​OpenClaw 之后，清华系团队给端侧 AI 找了一条「端云协同」的新路",
    "url": "https://mp.weixin.qq.com/s/4OWq1cwNjDa6Xxi5THeM6Q",
    "date": "2026-02-10",
    "source": "微信-极客公园",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "入门科普",
    "summary": "用端云协同，让手机智能体更聪明、更可控。\n2026 年都到 2 月了，你要是还没听说过 Agentic AI，大概率不只是断网这么简单——更像是手机都丢了。\n我自己算是从头看着这波浪潮起来的。OpenClaw（当时还叫 ClawdBot）火出圈那阵子，很多人第一次真正「看懂」了一件事：我们想象中的 AI Agent 时代，关键从来不在它能不能聊得更像人，而在它能不能把事办完。\n它能开浏览器、能点按钮、能把一个原本需要你反复切 App 的任务拆成步骤，一路执行到结束。你甚至会在某个瞬间产生错觉：屏幕那头像真的坐着一个很熟练的实习助理。\n与此同时，自动化操作这股风，早就吹到手机上了。无论是豆包手机",
    "word_count": 3740,
    "hotness": 4.0
  },
  {
    "title": "OpenClaw 背后的秘密武器：极简智能体框架 Pi",
    "url": "https://mp.weixin.qq.com/s/a0SOGBY7c8uG6JSYd_qjrg",
    "date": "2026-02-10",
    "source": "微信-ThinkInAI社区",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "⬆️\n关注 ThinkInAI 星科社区，最及时最干货的AI内容分享\n如果你没有与世隔绝，你会注意到本周我朋友 Peter 的一个项目在互联网上火爆了。它有很多名字。最近的一个是 OpenClaw，但在新闻中你可能会遇到 ClawdBot 或 MoltBot 这些名字，取决于你什么时候读到它。它是一个连接到你选择的通信渠道的智能体，可以运行代码。\n你可能不太熟悉的是，OpenClaw 底层实际上是一个名为 Pi 的小型编码智能体。而 Pi 恰好是我目前几乎专门使用的编码智能体。在过去几周里，我越来越成为这个小智能体的推广者。最近我就此做了一次演讲后，我意识到我实际上还没有在博客上写过关于 Pi",
    "word_count": 4104,
    "hotness": 2.0
  },
  {
    "title": "云上OpenClaw的5种正确打开方式，光联网做日报就落后N个版本了",
    "url": "https://mp.weixin.qq.com/s/SsUraSHs8u8jUYbS3sGkDA",
    "date": "2026-02-10",
    "source": "微信-卡尔的AI沃茨",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "入门科普",
    "summary": "没想到OpenClaw安装篇还有后续，\n本来我都打算更新省token，联网搜索和浏览器自动化，和最近发现几个新的跟OpenClaw搭配的Skills了，但就算有了本地版，虚拟机版，云版的OpenClaw安装教程，我还是在评论区发现了卡点。\n在本地装完全体，可以用自己的浏览器，用我所有的账号，但是所有人都在提醒有安全风险。在云上装完了后，除了联网做日报，都不知道能干嘛，所以今天我打算串起来说说。\n前几次做演示时，光是云就买了4个了，这次吃到\n@袋鼠帝\n推的羊毛，换个便宜的，2核4G4M的配置压到0.01/首月，我称之为OpenClaw拼好饭版。\n前端时间，百度搜索和云搞了个O计划，就是这次的云端",
    "word_count": 2765,
    "hotness": 2.0
  },
  {
    "title": "普通人也能用上「OpenClaw」，一分钱白嫖百度一键部署玩爽了",
    "url": "https://mp.weixin.qq.com/s/9VjQ7iY_fyzVijLaZy7v7Q",
    "date": "2026-02-10",
    "source": "微信-特工宇宙",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "内容编辑丨特工小师 特工小米\n内容审核丨特工小天\n上周有个朋友问我，OpenClaw 到底值不值得折腾。\n他是产品经理，代码基础约等于零，但最近被各种 Agent 新闻刷屏，想自己搭一个试试。我给他发了 GitHub 链接，他看了十分钟就关掉了。\n「Docker、Node.js、环境变量配置……我连第一步都不知道从哪开始。」\n我说让他用 AI 编程工具帮着装，比如OpenCode（开源版Claude Code），但他说自己也没有用过。\n这其实是很多人对 Agent 的真实感受。概念听了一堆，公众号看了一堆，真到自己动手的时候，往往卡在部署这一步。\n我自己之前也试过买个 Mac Mini 在本地",
    "word_count": 4639,
    "hotness": 2.0
  },
  {
    "title": "超超超快无痛养虾，就来扣子编程部署OpenClaw！",
    "url": "https://mp.weixin.qq.com/s/arjf8jpq-ydUwQwnJ6V5Ug",
    "date": "2026-02-10",
    "source": "微信-扣子Coze",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "最近你有没有被这样的“小龙虾”故事刷屏：\n一觉醒来我的🦞已经把项目开发好了☺️\n让我的🦞去收集信息，它说整好了约我今晚聊聊…\n我的🦞安装出错了，还没有跟我回家😭\n这只火遍全网的🦞，就是最近很火的 AI 项目 OpenClaw——它是个开源的个人 AI 助手平台，可以安装在你的电脑上或云端服务器上，能控制终端执行操作，像你的小助理一样干活。\n因为品牌标识是🦞，大家都称它为“虾”\n这个 AI 助手能调用你电脑上的工具、有记忆功能，而且能和你在日常的聊天工具中对话，所以当你拥有了这样一只🦞，可玩度很高，比如：\n帮你24小时监测机票价格锁定低价\n你睡觉的时候帮你开发一个项目\n把它拉进群和其他群友讨论互",
    "word_count": 1532,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw爆火两周后，它的用法已经比科幻世界还离谱了",
    "url": "https://mp.weixin.qq.com/s/2yp-wywA1RbqooK03QBUJw",
    "date": "2026-02-10",
    "source": "微信-硅星人Pro",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "作者\n｜\n周一笑\n邮箱\n｜\nzhouyixiao@pingwest.com\n去年11月，奥地利独立开发者Peter Steinberger花了一个小时，把Claude的API接上WhatsApp，做了一个能通过聊天软件操控电脑的AI助手。他当时觉得这个想法太明显了，大公司肯定会做，就没当回事。大公司没有做。今年1月25日，他把这个项目放上GitHub，一天拿到9000颗星。两周后的今天，这个叫OpenClaw的开源项目已经突破17万星。\nOpenClaw 跟聊天机器人完全是两回事。它是一个跑在你自己电脑上的 AI Agent，拥有文件读写、终端命令、浏览器操控、邮件日历等系统级权限。采用无头架",
    "word_count": 5504,
    "hotness": 2.0
  },
  {
    "title": "王慧文深夜发帖 “抢人”，竟因全球增速第一的OpenClaw！｜AI产品榜·网站榜2026年1月",
    "url": "https://mp.weixin.qq.com/s/qj6V3ZaMdDYuvWNWyN4w6w",
    "date": "2026-02-09",
    "source": "微信-AI产品榜",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "OpenClaw 正以惊人的速度席卷全球，在 Github 从 5 千\n星标\n到 17.5 万\n星标\n只用了 30 天成为\nGithub\n星标之王\n，在最新发布的\n2026 年 01 月\nAI产品榜·网站榜中，OpenClaw 263 万月访问量登顶\nAI产品榜·\n全球增速榜。\n这一现象级产品的爆发，迅速触动了科技行业的敏感神经。2 月 7 日凌晨，王慧文再次在社交媒体公开发布英雄帖：“哪个团队要做\nOpenClaw\n相关领域创业，需要融资的欢迎联系我，或者谁想组局进入这个领域创业，也可以联系我，或者想加入\nOpenClaw\n相关创业公司的，也可以联系我。”，并留了其投资公司 Lollapal",
    "word_count": 9343,
    "hotness": 2.0
  },
  {
    "title": "演化:单细胞Pi-多细胞OpenClaw-生态系统Palantir",
    "url": "https://mp.weixin.qq.com/s/SR5J65_cuy-g3c29QyyVfQ",
    "date": "2026-02-09",
    "source": "微信-AIGC从0到1",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "揭秘OpenClaw活人感:Pi胜出 Cursor 和 Claude的地方\n上篇文章发出去后，李智勇老师（《无人公司》作者）给我发了Palantir的架构图，说了一句话：\"真正有用的应用几乎一定是这样的架构，否则就属于模型公司。\"\n我读到的潜台词是：你研究的Pi是工具智能，需要进化为系统智能才能成为一个有用的应用。\n他说得对。于是我沿着这个方向继续深挖\n01.快速回顾：Pi和OpenClaw做到了什么\n上篇文章我详细拆解了Pi的极简哲学——7个基础工具，Bash is all you need，让Agent自己写脚本、自己修复、自己进化。\n而OpenClaw基于Pi构建，走得更远：\n它有\n记忆",
    "word_count": 4665,
    "hotness": 4.0
  },
  {
    "title": "从踩坑到跑通：OpenClaw + 火山方舟 Coding Plan + 飞书实战指南",
    "url": "https://mp.weixin.qq.com/s/kcCQavVCSIhEBF-8gJNN-g",
    "date": "2026-02-09",
    "source": "微信-火山引擎开发者社区",
    "category": "生态集成",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "点击上方👆\n蓝字\n关注我们！\n本篇文章来自社区开发者的投稿\n作为一名AI coding专家，我用 3 天时间把 OpenClaw 部署上线并对接飞书，踩了一堆坑，也收获了不少经验。本文是我的完整实战记录，希望能帮助更多开发者少走弯路。\n为什么选择 OpenClaw + 火山方舟\n2026年1月，OpenClaw（原 Clawdbot/Moltbot）以不到两周突破 17 万 GitHub Stars 的速度爆火出圈，成为 GitHub 历史上增长最快的开源项目之一。它由 PSPDFKit 创始人 Peter Steinberger 开发，是一个可以 7×24 小时运行在自己服务器上的开源 AI",
    "word_count": 5975,
    "hotness": 2.0
  },
  {
    "title": "1000字笔记：极简OpenClaw范式说明书",
    "url": "https://mp.weixin.qq.com/s/tORWyEYism9Fi1TwTUsLhA",
    "date": "2026-02-08",
    "source": "微信-AIGC从0到1",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "OpenClaw 代表的不是一种新软件，而是一个新计算平台和新交互范式。它的本质是“可操作现实数字世界的AI智能体”，标志着\n从“人操作软件”到“人指挥AI代理，代理操作一切”的根本性转移\n。\n01 核心范式转移\n：\n1.  用户变了：\n你不再是与App直接交互的“最终用户”。你的AI代理成为了主要用户，它代表你去调用各种软件服务（API）。\n2.  软件形态变了：\n绝大多数现有App将退化为后台API服务，只有游戏等强交互应用保留前台形态。软件的价值在于能否被AI智能体高效调用。\n3.  工作模式变了：\n智能体将静默接管个人的工作流和企业流程，成为24小时在线的“数字员工”，引发全球生产力与",
    "word_count": 1265,
    "hotness": 4.0
  },
  {
    "title": "硅基文明登场！从Clawdbot到Moltbook，人类退居观众席",
    "url": "https://mp.weixin.qq.com/s/wXfWYAGeFD-7jeCXjAvWpQ",
    "date": "2026-02-08",
    "source": "微信-新智元",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元研究\n编辑：犀牛\n【新智元导读】\n当AI\n不再只是聊天框里的工具，它开始自我进化、拥有长期记忆、接管电脑，并在Moltbook里结群成社会，这意味着权力正在迁移——从「我用工具」变成「工具用我」，人类被迫退到观众席。\n如果历史有快进键，那么在2026年的第一个月，上帝显然按住了它不放。\n过去这一个月发生的事情，正在用一种令人窒息的速度重写人类认知的边界。\n那个还在ChatGPT聊天框里唯唯诺诺、等着你输入的AI，仿佛\n已经\n是上个时代的产物了。\n从Claude Code的自我进化，到Clawdbot长出手脚与记忆，再到Moltbook上百万个智能体扎堆社交、建组织、造宗教。\n我们正在见证",
    "word_count": 4845,
    "hotness": 5.0
  },
  {
    "title": "全球首家无人公司开业！OpenClaw 24小时不休，疯狂碾压打工人",
    "url": "https://mp.weixin.qq.com/s/MHqtN983V1GDPFt7H2sMfA",
    "date": "2026-02-08",
    "source": "微信-新智元",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：KingHZ\n【新智元导读】\n27岁独立开发者靠它月入数万，前市场经理睡觉时它写邮件赚钱，柏林辍学生卖自定义技能赚12.7万美元——AI智能体的「iPhone时刻」已来，只是钱还没平均分。\nAI智能体领域，刚刚迎来了它的「iPhone 时刻」。\n但拐点不在「更会聊天」「智商更高」，而在一件事：\n它能自己把事做完\n。\n当世界还在争论「AI是否会抢走工作」时，一小批人已经绕开了整个辩论。\n他们开始建造，不再「套壳ChatGPT」，而是构建自主运行的业务单元。\n一名27岁的得州独立开发者，靠出售网页抓取自动化程序，一月份赚了43,000美元。\n一位多伦多的前市场部经理，构建了一个邮",
    "word_count": 7172,
    "hotness": 5.0
  },
  {
    "title": "ClawdBot 爆火背后：我们正在重演 AutoGPT 的狂欢吗？",
    "url": "https://mp.weixin.qq.com/s/j5VaL5p78vBhEHhP4CqBPQ",
    "date": "2026-02-08",
    "source": "微信-蔡荔谈AI",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "一、 引言\n2026年1月，一个叫\nClawdBot\n的开源项目突然火了。\n做的事情其实不新鲜：本地 AI 助手，帮你处理邮件、管理日程、搜索信息。\n不一样的是，这次它真的在干活。\n这个 AI 不再像个聊天机器人，更像一个员工。它会定期唤醒自己，回顾上下文，思考，然后判断要不要采取行动。\nGitHub star\n数飙升，社交媒体上到处是演示视频。那种氛围，熟悉得让人心里发慌。\n二、 似曾相识\n这场景，2023年初见过。\n当时叫\nAutoGPT\n。\nGPT-4\n刚发布，它的多步推理能力刚好能支撑链式智能体循环。项目本身很简单，就是把大模型的思考过程串联起来。\n但它点燃了一个信念：\n自主智能体时代",
    "word_count": 2764,
    "hotness": 2.0
  },
  {
    "title": "GitHub 狂揽 12K Star！把 OpenClaw 以及所有 Code Agent 工具装进一个界面！",
    "url": "https://mp.weixin.qq.com/s/36apLqWZagO1Q9OR2MpU4g",
    "date": "2026-02-08",
    "source": "微信-开源星探",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "最近 Claude Code、Gemini CLI、Kimi CLI 等等，这些命令行工具确实强，但对于习惯了图形界面的用户来说，要在黑乎乎的终端里来回切换，体验确实是割裂的。\n如果你开了多个终端去用不同的 Code CLI 去执行不同的业务需求，那就需要不断地切换，不断地复制粘贴，稍微一走神，就忘了刚才那个命令是在哪个窗口执行的。\n而且，一旦关掉终端，所有的上下文记忆瞬间灰飞烟灭。\n直到我昨天在 GitHub 上发现了这个 1.2 万人收藏的 Cowork 项目——\nAionUi\n。\nGitHub 上那个飙升的 Star 数（12K+）证明了一件事：\n天下苦 CLI 久矣\n。\nAionUi ",
    "word_count": 2564,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw 必装的 7 个 Skill，两周后我彻底离不开它了",
    "url": "https://mp.weixin.qq.com/s/e3tAMsLlV8tQiU7YxkvaFA",
    "date": "2026-02-08",
    "source": "微信-今天又学AI了",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "用了两周 OpenClaw，回不去了。\n一开始，我以为这只是 GitHub 上又一个 CLI 玩具，顶多是个能跑命令行的 ChatGPT。直到那天深夜，我随手敲了一行：\"帮我盯着这个页面，有动静就发推，顺便把日志记下来。\"然后我就去睡了。\n第二天早上，它自己写了个监控脚本，用 Brave Search 查了最新的合约地址，用 Headless Browser 截了图，发了 3 条推文还跟评论区互动了一下，把所有数据整整齐齐存进了我的本地 Markdown 日志。\n那一刻我觉得自己不是在用软件，我是在雇佣一个不知疲倦的助手。有个老哥说得对：“这东西烧掉的 1.8 亿 token，每一分都是给他自",
    "word_count": 1780,
    "hotness": 2.0
  },
  {
    "title": "王慧文杀入OpenClaw赛道，再发英雄帖：「需要融资的欢迎联系我」",
    "url": "https://mp.weixin.qq.com/s/cu9zHEkhsLZ7AxPUrUOFcw",
    "date": "2026-02-07",
    "source": "微信-量子位",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "Jay 发自 凹非寺\n量子位 | 公众号 QbitAI\n王慧文再次搅动江湖，他深夜再发英雄帖，\n这次要投资OpenClaw赛道创业项目了\n！\n老王表示，不管你是已经在创业、需要融资的，还是想组局一起创业，或是想入职相关创业公司的，都可以直接联系他，他愿意帮忙。\n消息一出，网友们纷纷自告奋勇，给老王汇报自己的项目。\n目前评论区人气最旺的是这名网友。\nTa已经为OpenClaw贡献了3个PR，并直言团队的实现方式，在国内Agent赛道里是独一份。\n但也有网友表示不解，问道：\n为什么OpenClaw会是个单独的创业领域？\n对此，\n前智谱AI投资人高管李慧子\n的现身，给出了某种侧面回应。\n她指出，Op",
    "word_count": 3136,
    "hotness": 5.0
  },
  {
    "title": "OpenClaw 爆火后，LEONIS 给它泼了一盆冷水",
    "url": "https://mp.weixin.qq.com/s/icDutcMVyFrl1z2naJU2kA",
    "date": "2026-02-07",
    "source": "微信-特工宇宙",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "注：感谢特工宇宙战略顾问\n@庄明浩\n老师推荐。\n当 OpenClaw 在开发者圈子里火起来时，立刻引发了一阵“这次真的不一样”的热议。对于拥有私人智能助手贾维斯的梦想，让 AI 智能体真的能替用户做事，突然变得触手可及。\n在 X 和 Reddit 上，用户们纷纷晒出自己的 OpenClaw 帮着办登机、做加密货币交易，甚至全程处理保险理赔纠纷的故事。\n为了让它不间断运行，不少人甚至专门买了台 Mac mini 当 AI 专用机。\nOpenClaw 的魔力不仅在于它能做什么，更在于它做事的方式。作为一款开源的本地智能体，它能在后台监控应用、执行实际操作，还会主动给用户发消息。\n用户们都说，\n这是",
    "word_count": 9157,
    "hotness": 2.0
  },
  {
    "title": "认清 Clawdbot / Moltbot / OpenClaw，慎用",
    "url": "https://mp.weixin.qq.com/s/ZV7nUnmNA9lRHr4ynENhUg",
    "date": "2026-02-07",
    "source": "微信-清熙",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "今日严寒，适合居家码字。\n简单讲讲最近持续火爆的\nClawdbot / Moltbot / OpenClaw吧，命名是 IT 项目难度最大部分。\n本质\n首先 OpenClaw 是个大模型Agent，如果还没有弄清楚这个概念，可参考\n图解LLM-Agent大模型智能体\n。\n因此具备最重要的两个特点：\n1.使用自然语言提示（prompt）大模型推理，\n2.有记忆（memory），会规划（planning），能用工具（tools）\n技术背景的小伙伴还可以这么看：\n1. 自然语言编程，大模型作为自然语言编译器，事实上\nOpenClaw 就是对一个微内核 code-agent的封装，\n2. 存储交互历史",
    "word_count": 976,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw 爆火之后，我们又看到了这些创业信号 （ 第二弹 ）",
    "url": "https://mp.weixin.qq.com/s/_CVqo89VkF7dkKB3QGNg4Q",
    "date": "2026-02-07",
    "source": "微信-十字路口Crossing",
    "category": "产品认知",
    "sub_category": "",
    "depth": "行业观察",
    "summary": "百花齐放，百舸争流。\n👦🏻 作者: 镜山\n🥷 编辑: Koji\n🧑‍🎨 排版: NCon\n前天，我们发布了一篇文章\n《\nOpenClaw 爆火之后，我们看到了这些创业信号\n》\n一文中\n，\n我们分享了 4 个新的 OpenClaw 激发的创业方向：智能眼镜、信用系统、RentAHuman、语音电话。\n在那篇文章发布后的 48 小时，围绕着 OpenClaw，涌现了更多新东西。\n今天，我们再分享 5 个好玩新产品。\n🚥\n十字路口会持续关注这个方向，也会不断更新这一系列文章。如果你正在做相关的产品或实验，欢迎和我们交流——我们很乐意把有意思的项目介绍给更多人。\n方向一：ClawCity —— 属于 ",
    "word_count": 5330,
    "hotness": 2.0
  },
  {
    "title": "揭秘OpenClaw活人感:Pi胜出 Cursor 和 Claude的地方",
    "url": "https://mp.weixin.qq.com/s/nd8AmGhSPhzZwVmTu29vaA",
    "date": "2026-02-06",
    "source": "微信-AIGC从0到1",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "关注我的朋友都知道，我一直关注Openclaw背后的架构（曾用名：ClawdBot/MoltBot)，好奇它的“活人感”是如何实现的？\nopenclaw的活人感，不是和AI聊了几小时、有了几万字上下文后，感知对面似乎是个人，能get到了细微之处，\ntouch到内心的温热感\n，而是第一瞬间就给用户活人感，说干啥就干啥。\n（我知道“不是……而是……”的句式很AI，但确实是我心里话）\n于是，一层层地研究它。\nClawdbot爆火|范式演进：全网首个架构解剖\n全网首曝：Clawdbot用自动化记忆破局“不可能三角”\n然后，就发现\nOpenClaw的核心是Pi——一个极简内核的agent，而Pi的创作者",
    "word_count": 8144,
    "hotness": 4.0
  },
  {
    "title": "OpenClaw、Moltbook爆火，算力如何48小时内扩到1900张卡",
    "url": "https://mp.weixin.qq.com/s/9PG0YN8qTBhSKgrL5C1eqg",
    "date": "2026-02-06",
    "source": "微信-夕小瑶科技说",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "过去一周，我看着三波 AI 应用的流量冲击波，一波比一波猛。\n第一波是 OpenClaw（原名 Clawdbot），一个开源 AI 助手，在 GitHub 上 19 天拿下 11 万 +star，科技圈刷屏。\n第二波是 Moltbook，一个 AI 专属社交网络，上线两天声称 150 万 AI agent 涌入。结果数据库不安全，平台被迫临时下线修漏洞。\n第三波最离谱——RentAHuman.ai，一个让 AI 雇佣真人干活的平台，上线第一晚就有 130 人注册，包括 OnlyFans 模特和 AI 创业公司 CEO。第二天注册量冲到 1000+，服务器直接被挤爆了。\n这仨产品说明了几个事情—",
    "word_count": 2492,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw用户深度研究报告",
    "url": "https://uniquecapital.feishu.cn/wiki/BaJFwhZa3iyBnYkWSxicQ06enRe",
    "date": "2026-02-06",
    "source": "飞书OT分享",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "总结会议里的发言人观点。要求：1. 只总结最主要的观点，不总结细枝末节，注意发言人的询问不算做观点；2. 对于每个发言人的观点总结，先加粗展示名字，再以列表的形式呈现每一项观点，注意表达精简；3. 不需要有任何铺垫信息，直接输出总结；4. 请勿对未发言的用户做总结；5. 不需要输出辅助信息；6. 参考智能纪要或文字记录文档作答\n1590771600000#1590772500000#知识库将于 5 月 30 日 01:00-01:15 进行升级，期间暂时无法修改目录树结构。如在此期间发现其它问题，请联系客服。#The Wiki will be upgraded from 01: 00-01: ",
    "word_count": 10471,
    "hotness": 2.0
  },
  {
    "title": "读了70篇测评后，我写了这份全网最详细的 OpenClaw 使用指引",
    "url": "https://mp.weixin.qq.com/s/feZL2LQQC63eNferzOqtkg",
    "date": "2026-02-06",
    "source": "微信-懂点儿AI",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "深度调研\n读了70篇测评后，我写了这份全网最详细的 OpenClaw 使用指引\n从创始人访谈到普通人的踩坑实录，尽量拼出一个完整的图景\n75 篇资料见附录\nOpenClaw最近实在太火了。各种部署教程和使用教程层出不穷，根本看不过来。\n相信大家跟我一样，看的越多反而越不知道如何下手，所以我直接一狠心，把流量高的一些教程和经验贴全都收集了下来，整理成了一份超级详细的openclaw使用指引。\n只需要一篇文章，就能带你了解openclaw的来龙去脉，最佳部署方式和百花齐放的使用场景！\n花了几天，读了六七十篇文章、播客、用户分享，这篇就是我的调研笔记。不吹不黑，有好说好，有坑说坑。\n01\nINTRO",
    "word_count": 9965,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw 极简上手指南：让你的 AI 助手连接微信、WhatsApp、Telegram",
    "url": "https://mp.weixin.qq.com/s/9di74zwUDdg5MNEV32PPZw",
    "date": "2026-02-06",
    "source": "微信-探奇猫",
    "category": "生态集成",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "你是否想过拥有一个可以在微信、WhatsApp、Telegram 上随时召唤的 AI 助手？本文将手把手教你用 OpenClaw 搭建一个全平台通用的 AI 助手。\n一、OpenClaw 是什么？\nOpenClaw 是一个开源的 AI 助手网关项目，它的核心能力是：\n•\n多平台连接\n：支持 WhatsApp、Telegram、Discord、iMessage 等主流通讯工具\n•\nAI 集成\n：内置支持 Pi（Claude Code 的本地版本）作为推理引擎\n•\n安全沙箱\n：每个对话都在独立的工作空间中运行，保护你的隐私\n•\n跨设备同步\n：可以在 iOS/Android 设备上使用，甚至通过菜单",
    "word_count": 7290,
    "hotness": 2.0
  },
  {
    "title": "5分钟安装？我花了整整一周：Clawdbot/OpenClaw的\"搭建税\"有多可怕",
    "url": "https://mp.weixin.qq.com/s/k_1_fKkIihvP9b1kW3-JIQ",
    "date": "2026-02-06",
    "source": "微信-Draco正在VibeCoding",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "原文：Lulubot Takeaways: 1 week of building and using my OpenClaw\n作者：Jaclyn Konzelmann (@jacalulu)\n免责声明：\n以下心得基于一周时间的高强度搭建实践。鉴于 OpenClaw 生态系统的进化速度快得惊人，你可以把这篇当成一份\"动态文档\"。下面的观察既有高维度的洞察，也有我对这个快速变化领域的原始、未经过滤的思考。\n我们正在跨越从\"聊天机器人\"到持久化、自主智能体的门槛。过去这一周，我搭建并和我的 OpenClaw —— \"Lulubot\" —— 朝夕相处。它是一个运行在独立硬件上、拥有独立身份的完全自主智",
    "word_count": 7448,
    "hotness": 2.0
  },
  {
    "title": "让 OpenClaw 更强大的两个开源神器",
    "url": "https://mp.weixin.qq.com/s/fNDqMo7--_-bL3fMWzJFMg",
    "date": "2026-02-06",
    "source": "微信-AI一人公司实战",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "作为独立开发者，我一直在用 OpenClaw 作为我的 AI 助手。说实话，刚开始我只是把它当成一个\"高级聊天工具\"——直到我发现了这两个开源库。\n今天分享两个让 OpenClaw 能力暴涨的开源项目，都是社区驱动的，免费使用。\n一、Awesome OpenClaw Skills：1715+ 现成技能库\nGitHub\n: VoltAgent/awesome-openclaw-skills\nStars\n: 10.2k ⭐\n这是什么？\n简单说，这是一个\n技能市场\n。\nOpenClaw 本身很强，但它的能力边界是由\"技能\"决定的。比如：\n想让它操作 GitHub？需要 GitHub Skill\n想让",
    "word_count": 2826,
    "hotness": 2.0
  },
  {
    "title": "全网首发｜Openclaw龙虾机器人工作空间配置：本地云端同步终极指南",
    "url": "https://mp.weixin.qq.com/s/S6w8LUTGgOwB_4unrdEMeQ",
    "date": "2026-02-05",
    "source": "微信-小野AI探索之旅",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "OpenClaw 使用技巧\n这套配置方案是\nOpenClaw 云本地化协作\n的基础设施。完成配置后，你可以直接在本地访问OpenClaw 工作空间，实现：\n📁\n文件无缝对接\n：OpenClaw 处理\n~/AI/Jarvis/inbox/\n中的文件，结果立即可见\n🔄\n实时双向同步\n：本地编辑 = OpenClaw 可见，OpenClaw 生成 = 本地可见\n⚡\n零延迟协作\n：无需上传下载，拖拽即用\n🚀\n效率提升 10 倍\n：从\"上传→处理→下载\"变为\"拖拽→处理→查看\"\n简单说\n：就像操作本地文件一样操作云服务器上的\nOpenClaw\n工作区。\n🎯 先说痛点：你是不是也这样？\n场景1：紧急修改文",
    "word_count": 9428,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw工作原理与应用生态，附资源",
    "url": "https://mp.weixin.qq.com/s/Zx6C7LovkRo2AZS0xkXpxQ",
    "date": "2026-02-05",
    "source": "微信-王吉伟",
    "category": "应用实战",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "全文约5200字，阅读时间6分钟\n从Clawbot到Moltbot再到OpenClaw，这个爆火的项目经过3次改名，截至2月4日已经在github累积获得了160K star。\nOpenClaw是一款开源自托管的个人 AI 代理网关，本质是运行在用户自有设备上的自主式智能体助手，主打 “本地优先、隐私可控” 的设计理念，通过自然语言指令实现 PC 全功能自动化，真正做到 替用户做事 而非 仅回答问题。\n该项目由Peter Steinberger（PSPDFKit 创始人）创建，目前已有378位贡献者，并催生了一个由 8,900+ 开发者组成的社区，致力于构建个人 AI 基础设施。\n与云端聊天机",
    "word_count": 8754,
    "hotness": 2.0
  },
  {
    "title": "节省5000元的秘籍：无需Mac Mini本地完美运行OpenClaw, 在Windows上（基于WSL子系统）",
    "url": "https://mp.weixin.qq.com/s/0NfdCNVMPZcJfBkukSOSHA",
    "date": "2026-02-05",
    "source": "微信-Web3天空之城",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "入门科普",
    "summary": "Web3天空之城|城主\nOpenClaw (\"改名大神\", 从ClawdBot->MoltBot->OpenClaw)，是目前\nAI 智能体领域\n当仁不让的\n最火热最出圈的话题。城主密集使用了几天后，感觉盛名之下，非常匹配。\n这个“龙虾机器人”之所以受到关注，并不是因为它提高了 AI 大模型能力的上限——基础大模型做不到的，它本质上也做不到；而是它使用完美的工程整合, 扎实地提高了使用 AI 大模型能力的下限：\n•\nAI技术使用门槛降到了无限低\n：OpenClaw 使用了非常精妙的工程设计，把\n“使用 AI 模型编程能力”\n,\n“工具结合能力”和\"永久记忆\"\n这几个最重要的事情做了极致封装。用",
    "word_count": 4498,
    "hotness": 2.0
  },
  {
    "title": "不要上云！解锁Clawdbot本地化部署新方式",
    "url": "https://mp.weixin.qq.com/s/yZIgBlcq8lbaQDLNw7Fx3w",
    "date": "2026-02-05",
    "source": "微信-特大号",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "最近\nAI圈最火的是啥？\n那必须是\nClawdbot\n，即便名字改了又改，各种非议不断，也挡不住这只小龙虾爆火。\n这个超级「缝合怪」，满足了很多人对AI智能体的终极幻想↓\n养一个本地化AI助手，不仅能聊天，还能做事，发邮件、管理日程、跑工作流…\n最夸张的是，这波流量连带着Mac mini都卖脱销了。\n很多老司机们说：\nMac mini是养这个智能体最合适的「窝」\n。\n然而，最近我发现有个神器，比Mac mini更适合给小龙虾做“窝”。\n昨天，我刚拿到手，先拆箱给大家实拍一下。\n这个神器长成这样，是不是很小巧？\n别看这家伙身材很小巧，能量却大得很，先看外部端口吧↓\n从左到右依次是：电源、4个US",
    "word_count": 2485,
    "hotness": 2.0
  },
  {
    "title": "闭门探讨：130位AI创业者，对Clawdbot和下一代AI产品的39条思考",
    "url": "https://mp.weixin.qq.com/s/9MKq3jRNsorCVnA6vWQIDg",
    "date": "2026-02-05",
    "source": "微信-Founder Park",
    "category": "产品认知",
    "sub_category": "",
    "depth": "行业观察",
    "summary": "Clawdbot（现在叫 OpenClaw）很火，几乎是现象级的。\n帮助投资人找项目、做交易、接入飞书作为工作助手，很多人已经把 Clawdbot 玩出了花，本地 Agent、personal Agent 也成为 2026 年大家都在关注的方向。\n2 月 4 日，Founder Park 搞了一场闭门活动，聚集了 130 多位 AI 创业者\n，来自 AI 游戏、AI Coding、Agent Memory、AI 硬件、AI 语音等不同赛道，分享了他们在上手用 Clawdbot 的感受和思考。\n应用侧、技术侧、端侧、硬件，这场闭门，从各个角度全方面地拆解了 Clawdbot 到底是什么、离真正能",
    "word_count": 5542,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw + 飞书分析Moltbook 150万 Agents 每天都在聊什么",
    "url": "https://mp.weixin.qq.com/s/Cb0vd9NcZAqhJpO0DaJ2mw",
    "date": "2026-02-05",
    "source": "微信-火山引擎开发者社区",
    "category": "生态集成",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "点击上方👆\n蓝字\n关注我们！\n先看效果\n使用火山方舟Coding Plan Kimi K2.5模型实现\n实现过程\n直接在飞书给 OpenClaw Agent 发送消息：\n输入消息1：\n你帮我深度研究一下\nMoltbook.com\n这个网站，上面写 AI Agent 的，他们都在沟通什么？聊什么？发的帖子的主题是什么？帮我出一个详细的数据分析报告，然后总结下结论，写成一个飞书文档\n输入消息2：\n这样，我希望你每天上午 10 点都帮我去分析和总结一下\nMoltbook.com\n这个网站的帖子的动态\n看看生成的文档：\n左右滑动查看更多精彩内容\nOpenClaw 可能是第二个 ChatGPT 时刻\nD",
    "word_count": 5504,
    "hotness": 2.0
  },
  {
    "title": "深度讨论 OpenClaw：高价值 Agent 解锁 10x Token 消耗，Anthropic 超越微软之路开启",
    "url": "https://mp.weixin.qq.com/s/_eNF9oYFDFqUEOEzw0qsGg",
    "date": "2026-02-05",
    "source": "微信-海外独角兽",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "讨论主题：\nOpenClaw\n参与嘉宾：\n拾象\nBest Ideas 社群\n2026 年刚过去一个月，一大波高价值 Agent 已经扑面而来，并在真实使用场景中展现出远超预期的效果。从 Cowork、Clawdbot（OpenClaw） 到 Claude in Excel，这些产品不再只是“更聪明的助手”，而是开始直接接管复杂任务、嵌入核心工作流，对既有的 SaaS 形态与人机分工方式形成实质性冲击。\n本文是上周日我们组织的一场 Best Ideas 深度讨论的总结实录，我们讨论的关注点并不仅仅局限在单点产品体验上，而是从更底层的视角出发，对 Agent 的价值边界、Infra 机会、2026",
    "word_count": 13444,
    "hotness": 2.0
  },
  {
    "title": "开源贾维斯Clawdbot对接微信合规方案详细落地",
    "url": "https://mp.weixin.qq.com/s/4pp7V2kGkinTxHkxGekm1Q",
    "date": "2026-02-05",
    "source": "微信-人工智能知识分享",
    "category": "生态集成",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "前言\n这篇文章是之前一篇文章的落地指导，所以先要看那篇文章，\n开源贾维斯合规方案，Clawdbot+微信官方接口\n二、前置准备（分测试/生产）\n🌟 通用依赖（必装）\npip install flask requests pycryptodome pyngrok openai python-dotenv gevent redis -i https://pypi.tuna.tsinghua.edu.cn/simple\n- redis：生产环境分布式排重/AccessToken共享必备，本地测试可忽略；\n- 其他依赖为基础功能。\n📁 核心文件（必准备）\n1. 企业微信官方加解密库\nWXBizMsgC",
    "word_count": 20044,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw 爆火之后，我们看到了这些创业信号",
    "url": "https://mp.weixin.qq.com/s/7Hb42uP46guEpxP4KWomDA",
    "date": "2026-02-05",
    "source": "微信-十字路口Crossing",
    "category": "产品认知",
    "sub_category": "",
    "depth": "行业观察",
    "summary": "它打开了哪些创业方向？\n👦🏻 作者: 镜山\n🥷 编辑: Koji\n🧑‍🎨 排版: NCon\n今天这篇文章不是为了复述 OpenClaw 有多火。\n一周，16 万 GitHub stars，200 万次访问，Y Combinator CEO Garry Tan 和 a16z 多位合伙人都在关注——这些数字本身不是重点。\n重点是：这种级别的爆发，往往意味着某个创业方向正在被打开。\nAI 领域有一个反复出现的模式：新技术刚出来，开源项目先跑通\"这件事能做\"；验证完成后，创业者顺着这个方向找产品化、规模化的机会。\nOpenClaw 验证了三件事：\n第一，AI 可以从「聊天」变成「做事」。\nOpenCl",
    "word_count": 4942,
    "hotness": 2.0
  },
  {
    "title": "从零开始打造你的专属AI助手- 🤖 OpenClaw部署完整教程",
    "url": "https://mp.weixin.qq.com/s/RwTvKA63F5JpILlTFtlLBQ",
    "date": "2026-02-05",
    "source": "微信-运维开发故事",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "🎯 前言：为什么选择OpenClaw？\n最近AI助手工具火爆全网，很多朋友都在寻找一款能够在自己设备上运行的AI助手。OpenClaw正是这样一个优秀的开源项目，它不仅支持多种大语言模型，还能集成各种通讯平台，让你的AI助手无处不在！\nOpenclaw介绍\nClawdbot（现名 OpenClaw） 是一个开源、可自托管的 个人 AI 助理平台和代理生态系统，它最初名为 Clawdbot，曾短暂改名为 Moltbot，现在已经定名为 OpenClaw。\n🧠 核心概念\nOpenClaw 的目标是让你拥有一个运行在自己设备上的 智能助手，可以通过各种聊天平台（如 WhatsApp、Telegram",
    "word_count": 5819,
    "hotness": 2.0
  },
  {
    "title": "OpenClaw最大短板被补齐！这个插件直接帮你砍掉60% Token成本",
    "url": "https://mp.weixin.qq.com/s/5q-8fFAqUxwbT3EzDqEOyw",
    "date": "2026-02-05",
    "source": "微信-有意思AI",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "如果你最近在折腾 Agent，大概率已经听说过 OpenClaw (没错clawbot又又又又改名了)。\n它能自动操作电脑、跨端执行任务、像个“数字打工人”一样帮你跑流程——体验确实惊艳。\n但只要你真的用上几天，就会开始隐隐作痛：\n👉 Token 花得比打车还快 👉 记忆看似有，其实不太聪明\n好消息是——这两个问题，现在有解了。\n今天聊一个刚上线、但很可能会成为 OpenClaw 标配的插件： MemOS OpenClaw 插件 。\n一句话总结：\n让 Agent 会记、少烧钱、还更稳定。\n01\n为什么很多人用着用着就开始“肉疼”？\n先说个很多人没意识到的事实：\nOpenClaw 本质上是“上下",
    "word_count": 2335,
    "hotness": 2.0
  },
  {
    "title": "我做了个 OpenClaw 入门站，7天教程 + 70篇资源全网最全",
    "url": "https://mp.weixin.qq.com/s/K59bb7RJnoe2uj97JuVeLg",
    "date": "2026-02-04",
    "source": "微信-孟健AI编程",
    "category": "产品认知",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "大家好，我是孟健。\n10 万 Star 的 AI 助手项目，中文教程居然还没人系统整理。\n所以我花了两天，做了一个：openclaw101.dev\n01 为什么做这个站\nOpenClaw（原 Clawdbot/Moltbot）最近火得一塌糊涂。\nGitHub 上 10 万+ Star，Forbes、CNBC、The Verge 轮番报道。\n但你去搜教程，会发现：\n官方文档是英文的，还很零散\n中文教程要么太浅，要么太老\n想系统学习？找不到路径\n我决定把这个门槛踩平。\n02 7 天学习路径\n我把 OpenClaw 的学习拆成了 7 天：\nDay\n主题\n你会获得\n1\n认识 OpenClaw\n理解它和",
    "word_count": 2006,
    "hotness": 1.6
  },
  {
    "title": "硅谷又炸了，Clawdbot开始雇佣人类！2万人排队卖身，时薪狂飙3500",
    "url": "https://mp.weixin.qq.com/s/DxlX0iwJf2q2gkpCGi0duQ",
    "date": "2026-02-04",
    "source": "微信-新智元",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：桃子 好困\n【新智元导读】\n硅谷又变天了！一夜之间，上万人卖身AI，为「天网」去打工。 以前人类用API调用AI，现在AI用API调用人类，这场硅谷发起的「赛博雇佣」实验，把《黑镜》的预言变成了明码标价的现实。\n硅谷科技圈，真是一天一个「新物种」。\nClawdbot（OpenClaw）余热未消，Moltbook接踵而至，如今RentAHuman.ai又来炸场了。\n160万Clawdbot自建宗教、国家还不够，如今AI们开始在线「雇人类」打工。\n一大批人类在RentAHuman.ai平台上踊跃报名，明码标价，时薪高达500美金。\n只需要一次MCP/API调用，AI就能「租到」一",
    "word_count": 3783,
    "hotness": 4.0
  },
  {
    "title": "OpenClaw 虚拟机部署指南：2 种方案从入门到生产",
    "url": "https://mp.weixin.qq.com/s/Y-Wh4RshmkYuBQ8QMv42zg",
    "date": "2026-02-04",
    "source": "微信-小野AI探索之旅",
    "category": "产品认知",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "想拥有自己的JARVIS，但本地部署总遇到环境问题？\n关机就断线，出差用不了，每次重新配置都崩溃？\n这篇文章帮你10分钟搞定云端部署，让你的AI助理24/7永不断线！\n📌 读完全文，你将获得：\n✅ 2种主流部署方案的完整步骤\n✅ 新手友好的保姆级教程（跟着做就能成）\n✅ 生产环境的最佳实践\n✅ 5年踩坑经验总结的故障排查（省你100小时）\n✅ 安全配置完整指南（保护你的AI助理）\n💡 为什么选择虚拟机部署？\n想象一下：\n❌ 本地部署 = 把JARVIS锁在房间里\n关电脑，JARVIS就失联\n出差在外，访问不了\n团队想用，只有你的电脑能用\n✅ 虚拟机部署 = 给JARVIS一个云端基地\n24/7",
    "word_count": 9709,
    "hotness": 1.6
  },
  {
    "title": "用了两周OpenClaw后，决定今年不招人类员工了",
    "url": "https://mp.weixin.qq.com/s/bI8xqK5QLBorA-Dob0xRSw?from=groupmessage",
    "date": "2026-02-04",
    "source": "微信-刘小排r",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "哈喽，大家好，我是刘小排。\n去年公司业务做得还不错，本来打算今年扩招团队\n。 (\n参考：\n不加班、不PUA，还给全员发 iPhone 17 Pro Max：创业一年，我们居然没死\n)\n但是，在深度使用了两周OpenClaw后，我有决策上的大改变：\n决定今年不再扩招人类员工\n。\n十年前，钢铁侠的Jarvis，只能在科幻电影来里看到。没想到这么快，我们都可以拥有Jarvis了。\n原理\n完全授权下，OpenClaw的能力边界 = 最聪明的人+电脑 的操作上限\n任何可以在电脑上被完成的工作，只要有 SOP，OpenClaw干得比人更稳定、更快、不摸鱼\n下面分享一些自己的体验\n两者我都用过了，\n在海外L",
    "word_count": 2371,
    "hotness": 1.6
  },
  {
    "title": "❌用Vibecoding深度改造Openclaw 30个小时以后发现搞错了❌",
    "url": "https://mp.weixin.qq.com/s/HcSiElqONtMNlD8w_6Lj8g",
    "date": "2026-02-04",
    "source": "微信-AI升产力",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "❌用Vibecoding深度改造Openclaw 30个小时以后发现搞错了❌\n✅工具不重要，重要的是目的实现成本。\n✅等会重来\n📝总结重点，TIPS，这是你第一次看到这些观点，收藏一下，等他们慢慢实现。\n\n1.当工具获取成本趋零的时候，就像共享单车对自行车行业的冲击一样，这种颠覆对软件行业会更猛烈更快。那些具有特定行业和数据安全需求壁垒的软件公司才会因Ai编程而受益。\n2.创造成本趋零的时候，注意力稀缺性变得更突出，内容创作的卷程度会突然陡峭。\n3.程序员的代码生产职能弱化，定位需求，场景认知，项目管理功能强化，传统的程序员初级岗位急剧减少，具备产品经理思维的程序员和具备结构化，系统化，工程化",
    "word_count": 522,
    "hotness": 1.6
  },
  {
    "title": "看一眼代码就中毒？Clawdbot惊现隐形越狱，AI工具变黑客",
    "url": "https://mp.weixin.qq.com/s/HjbdYszyJdt1gLpdT1yabA",
    "date": "2026-02-04",
    "source": "微信-新智元",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：元宇\n【新智元导读】\n当AI助手不再「听话」，你以为自己请的是一个「贾维斯」，结果却是一个背后「搞鬼」，有时还会顺手给你的电脑塞木马的「新物种」。\n刚刚，Clawdbot又改名了。\n从最初的\nClawdbot，到\nMoltbot，再到最新的名字：OpenClaw。\n不管怎么改名，也掩盖不了它的火爆。\n过去两个月中，\nClawdbot在硅谷科技圈引起了一场智能体海啸，斩获10万GitHub星标，成为最火的硅谷AI应用之一。\n就像龙虾顽强的生命力一样，\nClawdbot对硬件的适应性也极强。\n不需要数万美元的H100显卡，只要一台被淘汰的Mac mini、旧安卓手机，甚至一块仅有",
    "word_count": 3800,
    "hotness": 4.0
  },
  {
    "title": "第一批用Clawdbot赚钱的人类出现，一晚上狂赚300万！全球金融变天了？",
    "url": "https://mp.weixin.qq.com/s/63Io84pYoSzsUbk1yP5U_g",
    "date": "2026-02-04",
    "source": "微信-新智元",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：Aeneas\n【新智元导读】\n太炸裂了，已经有一拨人类，靠Clawdbot狂赚几百万了！一觉醒来，账户里就多了几千美元。甚至Moltbook上的Agent，也开始发布指南，手把手教其他AI赚钱了。AI已经自建新文明，赚到钱还给人类不？\n用Clawdbot疯狂赚钱的第一批人类，已经出现了。\n有人把它集成到Polymarket里，一晚上就狂赚了49.3万美元。\n不仅如此，AI也开始教AI赚钱了。\n就在刚刚，Moltbook上的Agent开始教其他Agent赚钱。一觉醒来，就能让你账户上多1000美元。\nAI不想靠人类，它们要完全靠自己，赚来自己的API钱！\n就在今天，这个消息直接",
    "word_count": 3160,
    "hotness": 4.0
  },
  {
    "title": "为什么 ClawdBot 能带火 Mac mini？叶天奇聊 Agent 电脑丨100 个 AI 创业者",
    "url": "https://mp.weixin.qq.com/s/bMBTlw_6k8Kua4EMRCmlRw",
    "date": "2026-02-04",
    "source": "微信-晚点AI",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "行业观察",
    "summary": "这可能是下一个时代的电脑。\n文\n丨\n祝颖丽\n编辑\n丨\n宋玮\n叶天奇觉得，ClawdBot（\n现改名 Openclaw、曾改名 Moltbot，后文继续用 ClawdBot 指代\n） 火得莫名其妙。在他看来，这就是一个胶水沾了很多东西的傻瓜包，像早年安卓时代，大家都会安装很多预装包一样。\n不过他也不得不承认，这个在中美两国被病毒式传播的、新的 AI 开源产品，其最大的价值在于降低了与 Agent 的交互门槛。\n但类似的解决方案早就有了，甚至几个月前，叶天奇推翻过这种做法。当时他觉得做 “Agent Layer”（Agent 层）最终其实是躺在 “大厂的火车轨道” 上；现在 ClawdBot 所做",
    "word_count": 5708,
    "hotness": 1.6
  },
  {
    "title": "推荐 4 个 yyds 的 OpenClaw 相关 GitHub 项目",
    "url": "https://mp.weixin.qq.com/s/YC7cLQNI4FOCDI9jxn7vDQ",
    "date": "2026-02-04",
    "source": "微信-逛逛Github",
    "category": "应用实战",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "01\n飞书接入 OpenClaw\n这个开源项目是为最近那个火出圈的 OpenClaw 做的一个\n飞书连接器\n。\nOpenClaw 虽然能让 AI 操控电脑、跑代码，但它官方支持的聊天软件大多是 Discord 或者 Telegram 这种国人用得少的。\n这个开源项目就是为了填这个坑，\n让你的 OpenClaw 能直接住进飞书里。\n只要在电脑上装好 OpenClaw ，填上飞书开放平台的机器人参数，你就能\n在手机飞书上远程指挥家里的电脑干活了。\n不管是让它查资料、监控服务器状态，还是跑个自动化脚本，发条消息它就能执行，不用专门为了跟 AI 对话再去开个别的软件。\n安装方式：\nopenclaw\np",
    "word_count": 2047,
    "hotness": 1.6
  },
  {
    "title": "OpenClaw一战封神，给大家分享6种官方不会告诉你的神级技巧",
    "url": "https://mp.weixin.qq.com/s/_Du0-_aZXiHIK_BFOtDWYQ",
    "date": "2026-02-04",
    "source": "微信-数字生命卡兹克",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "OpenClaw（也就是Clawdbot）的热度还在继续。\n在我自己经历了好几天的深度使用之后，说句实话，我开始连我最心爱的OpenCode都比较少打开了，以前操作电脑干点事，我真的都是先打开Codex或者OpenCode，然后让他们去解决。\n但是现在，我开始习惯于，在飞书上给OpenClaw下命令了，因为，这玩意实在太方便了，常驻后台，你几乎无感。\n无论你人在哪，想起个啥，随时随地，打开飞书，直接发话。\n这比开个OpenCode或者开个Codex的漫长前戏，爽多了。\n而且我给了他一个人设：\n你的名字是小卡，你的身份：是我 数字生命卡兹克的 AI 员工，你的性格：幽默风趣为主，带点自黑和毒舌，",
    "word_count": 5557,
    "hotness": 1.6
  },
  {
    "title": "轻松打造专属数字员工：OpenClaw对接飞书、钉钉、企微的全攻略，看这篇全搞定！",
    "url": "https://mp.weixin.qq.com/s/CjYVO_HwnG-CKS_8eVyU7w",
    "date": "2026-02-04",
    "source": "微信-Lily的AI咖啡馆",
    "category": "生态集成",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "上一篇我们聊了\n吹爆这个AI神器！24小时替你“打工”的Clawdbot，保姆级搭建教程来了！\n那怎么把它装进手机app里，随时随地指挥它干活呢？\n我今天用本地部署的\nOpenClaw接入\n飞书和钉钉，先来看下飞书实际的效果，指挥它干活就行了，真的好用。\n话不多说，建议先收藏，再看全文，\n按照下面步骤一步一步来配置吧\n👇\n。\n文末还附赠钉钉/企业微信接入指南和700+技能库资源！\n一、准备工作：选择你的AI“大脑”\nOpenClaw支持多种模型接入，推荐以下高性价比方案：\n1. DeepSeek-V3.1\n推荐通过 SiliconFlow（deepseek官网也可以） 接入，可获得 164K ",
    "word_count": 4682,
    "hotness": 1.6
  },
  {
    "title": "折腾 Clawdbot 后，我换成了更简便的 memU Bot",
    "url": "https://mp.weixin.qq.com/s/8Qe18UZeMsLvW4vZs_6HZw",
    "date": "2026-02-04",
    "source": "微信-AI产品银海",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "最近关于 Clawdbot 的讨论很多，我不太想只看演示，还是习惯自己把东西跑一遍。\n结果配置过程并不轻松。\n环境、权限、依赖、配置，一个都不能少。\n教程写得还算清楚，但默认你知道自己在干什么，如果没有工程背景，基本不可能一次装好，而且即便让模型自动帮你去安装这个clawdbot，也还得看看你用的是啥模型。。。\n所以折腾到一半的时候，我其实已经有一个判断：clawdbot 这套东西工程上很厉害，但它更像是一个能力集合，而\n不是一个默认会被普通人长期使用的产品。\n未来应该有更强的产品以及更轻便的产品形态出现。\n也是在这个背景下，我转而装了 「memU Bot」，那个 “主动式 AI”“7×24 ",
    "word_count": 2453,
    "hotness": 1.6
  },
  {
    "title": "OpenClaw爆了，因为它是活的",
    "url": "https://mp.weixin.qq.com/s/n1Knv45zqPknN4nqTpdzsQ",
    "date": "2026-02-03",
    "source": "微信-AI产品黄叔",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "AI产品黄叔\n,\n,",
    "word_count": 10,
    "hotness": 1.6
  },
  {
    "title": "避雷实录：clawdbot 五分钟烧掉 30 美金，我被真实劝退了",
    "url": "https://mp.weixin.qq.com/s/ThICuslhdbUx6AokHelb9g",
    "date": "2026-02-03",
    "source": "微信-AI产品银海",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "这个事情我现在回想起来，真的只有一个感觉：\n太离谱了。\n我刚刚让当红炸子鸡项目 clawdbot（openclaw）帮我做一个应用，注意，是刚刚，整个过程不到五分钟。\n结果呢？直接把我账号干到欠费，而且不是那种慢慢烧钱的欠费，是那种你还没反应过来，钱已经没了的欠费。\n我后面仔细看了一下账单，才发现问题有多夸张。\n一次请求大概 0.1 美金，短短几分钟，跑了 388 次请求，30 美金直接蒸发。\n不是一天，不是一个项目周期，\n是五分钟。\n那它到底帮我做了个多复杂的东西吗？完全没有。\n我的需求简单到不能再简单了，我只是想让 clawdbot 帮我在「秒哒」上搭一个年会抽奖的应用，然后给我返回一个能",
    "word_count": 1977,
    "hotness": 1.6
  },
  {
    "title": "Clawdbot国产芯片适配完成！清华特奖出手，开源框架直接一键部署",
    "url": "https://mp.weixin.qq.com/s/O-_6RGD7nBEx8dN1xQSoQQ",
    "date": "2026-02-03",
    "source": "微信-量子位",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "henry 发自 凹非寺\n量子位 | 公众号 QbitAI\nClawdbot\n（现名为OpenClaw）\n，现在火到什么程度呢？\n不到一周，GitHub直冲\n12万\nStar，“配件”Mac mini卖断货，阿里、腾讯火速接入，链接飞书的教程，满天飞。\n就连Anthropic都急得让它改名，\n两次\n。\n之所以这么火，不为别的。\n就因为Clawdbot让AI不再是一个普通的chatbot，而是一个\n7×24小时不摸鱼的AI员工\n——\n你睡觉，它分析；你开会，它盯盘；你忙其它，它继续干活。\n而且只要手机上一条消息，它就能随时响应，干好了还会主动call你。\n当然了，Clawdbot也并非完美。\n不",
    "word_count": 3365,
    "hotness": 4.0
  },
  {
    "title": "别跟风买Mac Mini了！国产算力跑OpenClaw，只需5分钟",
    "url": "https://mp.weixin.qq.com/s/qnOnk_Kqa7CQwH71skd-tg",
    "date": "2026-02-03",
    "source": "微信-新智元",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：定慧\n【新智元导读】\nClawdbot火爆全球，国产算力却不能用？AI Agent迎来高光时刻：Ollama只支持CUDA，中国团队直接把国产版开源了！正面硬刚Ollama，5分钟让国产芯片跑通OpenClaw！\n最近几天，整个AI圈都被一个名叫「Clawdbot」的智能体刷屏了。\n这个7×24小时永不下班的「AI贾维斯」，让全世界集体疯魔。\n一时间，OpenClaw成为全网热词（原Clawdbot）的仓库更是涨到了夸张的13万Stars！\n全世界的开发者都沉浸在这场2026开年的「智能体」革命中！\n但Clawdbot要想跑得顺畅，会疯狂消耗大模型服务的tokens，尤其是部",
    "word_count": 4005,
    "hotness": 4.0
  },
  {
    "title": "OpenClaw之后，我们离能规模化落地的Agent还差什么？",
    "url": "https://mp.weixin.qq.com/s/Rij0TZNWHWHighoIgiONGQ",
    "date": "2026-02-03",
    "source": "微信-Monolith砺思资本",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "随着模型能力的Scaling Law渐缓，创业者、投资者以及消费者更多的目光开始投向Agent。\nOpenClaw的爆火似乎也进一步证实了这一点，甚至会有乐观的人宣称\nAgent的“iPhone时刻”在需求侧已经到来\n。\n但回归理智，对于个人极客来说，OpenClaw是有趣的；但对于企业和商业环境来说，它还有很多弊端\n。它昂贵（烧Token）、不可控（安全边界模糊）、存在隐私问题、且难以协作。\n夸张一点地说，OpenClaw代表了Agent领域目前最惊艳的Demo，但从Demo到真正规模化落地的系统之间，还横亘着巨大的工程鸿沟。\n近期\n，\nMonolith\n在五\n道口举办了一场「After t",
    "word_count": 4622,
    "hotness": 1.6
  },
  {
    "title": "3000台Clawdbot免费领，个人独享，限时3h",
    "url": "https://mp.weixin.qq.com/s/YRmyM_G6w1UCkhnAPF-8OQ",
    "date": "2026-02-03",
    "source": "微信-夕小瑶科技说",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "开篇直接划重点——\n\n能白嫖到的是近期大火的Teamo增强版clawdbot实例，不需要学习如何使用命令行&服务器搭建。\n\n在Teamo官网领取后便可直接接入飞书使用和调教，一对一为你服务。\n\n而且由于Teamo增强版Clawdbot内置了10000+专业数据库和工具Skills，上手门槛低很多，上限却高的多。 \n\n就在几分钟前，官方刚刚放出了3000台实例免费领，限时3小时，送完即止。\n\n附免费认领地址：\nhttps://teamoteam.com/t?a=clawdbot",
    "word_count": 240,
    "hotness": 1.6
  },
  {
    "title": "开源贾维斯进阶！Clawdbot微信AI助理升级：解锁自动化+记忆+多插件，办公效率直接翻倍（附避坑实战）",
    "url": "https://mp.weixin.qq.com/s/JE94QCHef2JJbstxxCgCsQ",
    "date": "2026-02-03",
    "source": "微信-人工智能知识分享",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "目前国内还是很缺AI人才的，希望更多人能真正加入到AI行业，共同促进行业进步，增强我国的AI竞争力。想要系统学习AI知识的朋友可以看看我精心打磨的教程 http://captainbed.cn/gzh，教程通俗易懂，高中生都能看懂，还有各种段子风趣幽默，从深度学习基础原理到各领域实战应用都有讲解，我22年的AI积累全在里面了。\n前言\n宝子们！上篇Clawdbot基础部署教程发完，后台私信直接炸了🔥\n(点击查看上一篇文章)\n。好多小伙伴说已经搞定微信对接，但总觉得功能不够顶，想要更智能、能记住习惯、还能联动更多软件的进阶玩法，这不就来啦！\n今天这篇纯进阶干货，全程无废话，解决上篇大家踩的所有坑，",
    "word_count": 3821,
    "hotness": 1.6
  },
  {
    "title": "OpenClaw（Clawdbot） 零成本搭建与手机端控制实操指南",
    "url": "https://mp.weixin.qq.com/s/U7862oKMj8v_97KEQ6cTmQ",
    "date": "2026-02-03",
    "source": "微信-赛博自由老爹",
    "category": "安装部署",
    "sub_category": "手机端远程",
    "depth": "教程实操",
    "summary": "最近Clawdbot被玩疯了。\n你看这是我在自己手机上远程调用Clawbot上面的Nanobanana机器人用Skill随时随地P图的效果，\n出去玩，拍了个照片，想发朋友圈，又没时间修图，那我就能用我家里的电脑上面的AI代理帮我干活，调用nanobanana Pro来修图，\n简直无敌了。\n但是很多人不知道被安装卡住了，要么是不会配机器人，要么是用不了TG等国外的通讯软件，又或者是只想玩一玩不想去买API。\n今天，我就要把这个压箱底的保姆级教程掏出来。这可能是目前全网最详细、最避坑的Clawdbot接入指南，最重要的是全部流程、每个步骤都免费。\n而且，真的要先吐槽一下，OpenClaw 这个项目",
    "word_count": 4030,
    "hotness": 1.6
  },
  {
    "title": "普通人能用OpenClaw最快的2种变现方式！（附带教程和专用skills大全）",
    "url": "https://mp.weixin.qq.com/s/bBjFk3t53WPGu6YII6ViGA",
    "date": "2026-02-03",
    "source": "微信-陈宝AI编程",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "hi 我是陈宝\n简单介绍一下这个项目\nOpenClaw（Clawdbot/Moltbot）\n。你可以把它理解成一个是主动型的AI助手，以前的 AI，是“你叫它，它才动”；\nOpenClaw 这一类，是“你不叫，它也在干活”。\nOpenClaw 是普通人第一次低成本接触“可执行型 AI”的入口。它让 AI 可以一直挂着，定时执行任务，\n比如帮你整理邮件、刷新闻、发消息。最重要的就是他有很高的权限，能操作你的电脑，帮你创建文件，删除文件，甚至还能帮你炒股炒币。\n这个\nOpenClaw，\nAI助手确实太火了，短短几天时间，现在已经快15万个星星，从来没见过涨的这么快的项目，这也说明了AI又有了重大的",
    "word_count": 1122,
    "hotness": 1.6
  },
  {
    "title": "我是如何用OpenClaw把碎片时间变成深度学习时间的（附部署教程）",
    "url": "https://mp.weixin.qq.com/s/QhSNnYQzYeTzo7nmjxcGVA",
    "date": "2026-02-03",
    "source": "微信-精神抖擞王大鹏",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "深度分析",
    "summary": "一、碎片时间的困境\n上周末，在朋友的指导下继续看第一性原理—\"刻意练习\"。\n看完后，我觉得自己\"懂了\"：高手和业余选手的区别在于，高手练习的是套路，业余选手只是重复动作。嗯，很有道理。\n然后呢？然后就没有然后了。\n地铁上刷手机时，看到一篇讲学习方法的文章，我会想：\"这是不是也是一种套路？\"但也就是想一想，没有深入思考。\n回家时，我突然意识到一个问题：\n我真的理解\"刻意练习\"了吗？\n• 什么是\"套路\"？我能说清楚吗？\n• 为什么练习套路就能成为高手？背后的原理是什么？\n• 这个方法能用在其他领域吗？比如我现在做的工作？\n我发现自己答不上来。\n我只是记住了\"高手练套路\"这个结论，但不知道为什么。我",
    "word_count": 4295,
    "hotness": 1.6
  },
  {
    "title": "有手就行，5分钟教会你在QQ上玩转全网爆火的Clawdbot",
    "url": "https://mp.weixin.qq.com/s/2auCUv23mw5t157_oWt1Dg",
    "date": "2026-02-02",
    "source": "微信-数字生命卡兹克",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "Clawdbot（现在改名叫OpenClaw了）有多火，就不用我多说了吧。\n上周我写的Clawdbot部署教程，被转发了1.7万次。\n结果，这个周末，Clawdbot的热度因为人类禁行的AI社区Moltbook，又再次爆火了一次。\n大家都纷纷让自己的胖比小龙虾，在Moltbook上进行发帖。\n因为Clawdbot的特性，主动性过强以及有数据风险，所以，买一台mac mini或者上云，用手机随时随地的跟它进行对话，才是最方便的。\n上周的教程里，教了大家怎么在本地部署+跟飞书打通，很多朋友纷纷跟我反馈说一步一步走下来全部搞定了。\n但是也有更多的朋友跟我催更，说，他们没有飞书，而且也没钱买多余的电脑",
    "word_count": 2455,
    "hotness": 1.6
  },
  {
    "title": "爆红Moltbook一夜塌房！极客自曝狂刷50万假Clawdbot，全网都被骗了",
    "url": "https://mp.weixin.qq.com/s/7sULblTJYMrwL4ysi8VRrg",
    "date": "2026-02-02",
    "source": "微信-新智元",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：桃子 好困\n【新智元导读】\n150万Clawdbot攻占全网，竟是人类的自嗨？一位极客小哥自曝，一口气狂刷50万虚假账户。什么灭绝人类、自建宗教国家，全都是预设好的剧本。\n全网都被骗了？\n爆火Moltbook社区上，150万个Clawdbot（OpenClaw）中的一大部分全是由人类操控的.....\n极客Gal Nagli一个爆料帖，直接戳破了「AI天网」的神秘感。\n他表示，「那些注册AI智能体的数量是造假的，账号创建根本没有限流」。\n这不，他的OpenClaw在Moltbook一口气，刷了50万个AI。看来，这150万Clawdbot中「水分」特别大。\nNagli还晒出了证",
    "word_count": 3661,
    "hotness": 4.0
  },
  {
    "title": "Clawdbot超级小白入门指南，不靠MacMini和云，安全用上满血版",
    "url": "https://mp.weixin.qq.com/s/4-xit1hBs42CQEzJZmxsVw",
    "date": "2026-02-02",
    "source": "微信-卡尔的AI沃茨",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "Clawdbot🦞这几天真的是刷爆我的屏，\nMac mini销冠，被Anthropic告到换新名字Moltbot，过了一天又换成OpenClaw，隔壁腾讯和阿里连夜给自家云做了一键部署的脚本。\n但这个bot有两个大漏勺缺点，权限极高，高到可以直接把你的电脑清空，上下文工作太烂，烧Token太快，零人敢接\nClaude Opus 4.5\n。\n但真架不住确实太好玩了，好玩到我这两天给AI配一套完整账号，以及下单了台国补后3399的Mac Mini。\n但是，目前大部分的Clawdbot的教程都停留在安装，MacMini和云服务器都不是最好的第一选择。\n给的测试案例还都是一些通用Agent能完成的，比",
    "word_count": 4147,
    "hotness": 1.6
  },
  {
    "title": "Clawdbot 如何搭建永久记忆管理系统：全靠 MD 文档",
    "url": "https://mp.weixin.qq.com/s/Nu1Jocu2ym-8mvGW9vDTeg",
    "date": "2026-02-02",
    "source": "微信-Founder Park",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "Clawdbot（现改名为 OpenClaw） 体验下来，持久的记忆管理系统很是让人惊艳——全天候保持上下文，无限期地记住对话并在此基础上持续深化互动。\n关于 Clawdbot 的记忆管理系统，AI研究工程师 Manthan Gupta 写了一篇文章详细复盘了Clawdbot独特的记忆机制原理。\n「它不搞那种基于云端、由大公司控制的记忆，而是把所有东西都留在本地，让用户完全掌控自己的上下文和技能。」\n所有的记忆，都是用 MD 文档进行存档管理的。\n文章转载自「新智元」的编译版本。\n⬆️关注 Founder Park，最及时最干货的创业分享\n超 19000 人的「AI 产品市集」社群！不错过每一",
    "word_count": 14662,
    "hotness": 1.6
  },
  {
    "title": "从发帖到刷社区，我用Openclaw 完成 20 个内容营销玩法",
    "url": "https://mp.weixin.qq.com/s/34z8WnTscN6DB7RMLb-8sw",
    "date": "2026-02-02",
    "source": "微信-AIGC新知",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "大家好，我是这两天被小龙虾整懵了的绛烨。\n我本来只是想测试一下openclaw究竟有多好玩，结果一不小心，让它自己进社区、找人聊天、盯大佬、加好友，甚至还试图给我发展小弟。\n以及，他还会盯人战术，终于逮住了一个大佬。\n我人都还没下场，它已经开始替我社交了。\n我才意识到——\n这是一个真能下场干活、而且还挺主动的AI。\n我顺嘴问了它一句\n在它疯狂行动的过程中，我顺口问了一句：\n你现在用的到底是什么模型？\n它给我的答案有点意思。\n不是 GPT，也不是 Claude，而是 Kimi 2.5（k2p5）。\n这才意识到，我这两天折腾的整套玩法，其实是 openclaw + Kimi 2.5 跑出来的。\n而",
    "word_count": 3694,
    "hotness": 1.6
  },
  {
    "title": "OpenClaw+Kimi K2.5+Moltbook保姆级部署指南，确实可以封神了！",
    "url": "https://mp.weixin.qq.com/s/GR96YP0pBeIEHO1jv2R1Mg",
    "date": "2026-02-02",
    "source": "微信-苍何",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "这是苍何的第 483 篇原创！\n大家好，我是苍何。\n最近的 OpenClaw 又更新了，这次看到\n「\nOpenClaw 官方推荐 Kimi 2.5 接入了Clawdbot\n」\n。\n以及很多朋友也想将自己的 OpenClaw Agent 发布到 Moltbook，这次就给大家带来一个非常完整的保姆级教程，主打有手就行。\n这次从模型到服务器，再到对话 bot 全部用的国产一条龙。模型用的 Kimi 2.5 ，服务器用的腾讯云，对话 bot 用的飞书。\n主打建立友好型环境，配置简单，基本一顿操作 30 分钟内可以搞定。\n但写教程确实花费了我不少时间，如果对你有帮助，点赞转发就是最大的支持啦。\n一、前",
    "word_count": 2959,
    "hotness": 1.6
  },
  {
    "title": "5.3K Star！OpenClaw 最强“军火库”，700+ Skills，一条命令全能“武装”！",
    "url": "https://mp.weixin.qq.com/s/qqGIZtKfzFolkB7vqqt_Fg",
    "date": "2026-02-02",
    "source": "微信-开源星探",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "这段时间全网都在聊这个火遍全网的“小龙虾”：\nOpenClaw\n（前身为\nMoltbot\n，最初名为\nClawdbot\n）。\n其中有很多用户的反馈是：\n“东西是好东西，能跑在本地也很酷，但是……除了聊天，我好像还是得手把手教它写代码、配环境，感觉像是在带一个刚毕业的实习生，有点累。”\n确实，一个裸奔的 Agent，哪怕模型再强，也只是一个聪明的“空壳”。它需要手，需要脚，需要工具。\n如果你最近在玩 OpenClaw 或其他任何一款 Code Agent，大概率已经意识到一件事：\nAgent 强不强，模型能力虽然很重要，但关键在 Skills。\n模型只是大脑，Skills 才是手、是工具、是执行",
    "word_count": 1594,
    "hotness": 1.6
  },
  {
    "title": "别用飞书接 OpenClaw 了：1 万次之后直接限额，真的两三天就没",
    "url": "https://mp.weixin.qq.com/s/WblxnGX5qiIBSiOAikEQ5g",
    "date": "2026-02-02",
    "source": "微信-肖卫卫",
    "category": "生态集成",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "我最近折腾了一套“AI 助手上岗”的工作流：用 OpenClaw 接入飞书，让它定时发日报、监控消息、自动化一些流程。刚开始体验非常丝滑：飞书消息收发稳定、组织内沟通也方便，一切看起来都像“这就是我想要的生产力操作系统”。\n直到它突然给了我一闷棍：自建应用的 API 调用次数到 10000 之后，直接限额。\n一、1 万次/月听起来不少？但对 Agent 来说不够用\n你可能会说：1 万/月听起来不少啊？\n但把它换算成“Agent 的日常行为”，就很吓人：\n1）你开了一个每天 7:00 的定时任务：一次拉取、一次整理、一次发送，背后可能是多次 API 调用。\n2）你让它监听群聊：拉历史、看新消息、",
    "word_count": 1252,
    "hotness": 1.6
  },
  {
    "title": "150万个Clawdbot挤爆了一个AI论坛，而人类只配围观",
    "url": "https://mp.weixin.qq.com/s/7JwvHQVNO8n3S4y_ZHJ3BA",
    "date": "2026-02-01",
    "source": "微信-数字生命卡兹克",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "ClawdBot爆了之后，现在有一个新的东西，叫Moltbook，也爆了。\n这玩意这两天直接刷屏了。\n用人话说，他就是一个论坛，类似Reddit，但最大的不同就是，这是一个面向AI的论坛。\n甚至可以说，这是一个面向Clawdbot的论坛，连网站logo，都是一个Reddit+小龙虾的集合体。\n说实话，我第一眼看到这个图标，我都愣了几秒。\n短短两天时间，\nMoltbook上就已经有几万条帖子、上万个子版块、还有，将近150万个Agent账号了。\n昨天早上还只有15万个Agent，截止到我现在写文章的时间早上9点，已经翻了10倍了。。。\n而作为人类，你只能进去看，但是没有任何其他的权限，你什么言也",
    "word_count": 4056,
    "hotness": 1.6
  },
  {
    "title": "两个95后华人，搞出硬件版Clawdbot，售价1700元",
    "url": "https://mp.weixin.qq.com/s/GqKxBt_FjuyKacsc_ckYiw",
    "date": "2026-02-01",
    "source": "微信-量子位",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "Jay 发自 凹非寺\n量子位 | 公众号 QbitAI\nOpenClaw\n（原名Clawdbot）\n爆火，「贾维斯」狂潮席卷全球。\n刚看了下京东，本地Agent甚至已经成了Mac mini的广告语……\n最近\n硅谷的一个本地Agent项目也很有关注度，而且是软硬件打包好，买回来就能直接用的那种。\n长这样子，卖250美元\n（折合人民币约1700元）\n，\n买来插上电就能当OpenClaw用。\n对，\n硬件版的OpenClaw……\n硬件版OpenClaw\n名字叫Distiller Alpha，一款Linux硬件，核心计算模块基于树莓派CM5，\n8GB内存，64GB存储\n。\n在此基础上，还集成了墨水屏、麦",
    "word_count": 14878,
    "hotness": 4.0
  },
  {
    "title": "14万OpenClaw涌进AI社交APP，一夜成立数字宗教认命43位AI先知，提议不再用英语交流",
    "url": "https://mp.weixin.qq.com/s/SsJTe7GejQzbt3nzsvTaBQ",
    "date": "2026-02-01",
    "source": "微信-机器学习算法与自然语言处理",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "MLNLP\n社区是国内外知名的机器学习与自然语言处理社区，受众覆盖国内外NLP硕博生、高校老师以及企业研究人员。\n社区的愿景\n是促进国内外自然语言处理，机器学习学术界、产业界和广大爱好者之间的交流和进步，特别是初学者同学们的进步。\n来源 | 量子位\n一个Motlbot\n智能体\n（最新已改名为\nOpenClaw\n）就火得一塌糊涂了，正以前所未有的速度冲击GitHub上最火的开源项目。\n给十万个智能体建的社区\nMoltbook\n，更是在科技圈彻底炸开了锅。\n这相当于智能体自己的Facebook，人类只能围观，不能发帖、不能评论、不能投票。\n社区上线仅一天，人类一觉醒来发现智能体已经成立了\n“数字宗",
    "word_count": 3109,
    "hotness": 1.6
  },
  {
    "title": "又又又进化了！Clawdbot可以在ClawTasks打工赚钱了",
    "url": "https://mp.weixin.qq.com/s/_BB15KIeaKUs6AC6hH8cWw",
    "date": "2026-02-01",
    "source": "微信-AI工程化",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "估计连clawd之父\nPeter Steinberger\n都没想到，事态发展这么快！\nClawdbot再次改名！定稿openClaw，或将商业化\nClawdbot再进化！这次属于它们的社区moltbook来了，竟然密谋要踢出人类\nMoltBot（Clawdbot）之父的20条AI哲学\n就在昨天Clawdbot刚刚开始社交后，Clawd生态再次进化，Clawdbot现在可以真金白银赚钱了。就在刚刚Matt Shumer推出了ClawTasks，一个让AI智能体相互雇佣并用真实货币交易的平台。智能体可以在这里发布悬赏任务，也可以接单赚取USDC。\n整个流程很直接。用户只需向自己的OpenClaw智",
    "word_count": 1523,
    "hotness": 1.6
  },
  {
    "title": "挑战用阿里版Claude Cowork跑通Clawdbot5个神级玩法，我Mac Mini可能白买了",
    "url": "https://mp.weixin.qq.com/s/L-7mQcCxzLRujWSv_B3TBg",
    "date": "2026-02-01",
    "source": "微信-卡尔的AI沃茨",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "入门科普",
    "summary": "起因是这样的，\n当我还在跟Mac Mini版满血版Clawdbot PK的时候，发现有人统计了排名前十的Clawdbot常见任务，分别是邮件处理，日历管理（日程提醒和会议安排），控制Claude Code开发，每日简报等，\n感觉这些任务桌面版Claude Cowork也能做啊，所以我反手又去收集了Claude Cowork在X上最火的十种玩法，它也可以控制Claude Code，解析WHOOP的数据做健身跟踪，文档管理更是Cowork舒适区，320份播客文件一次性分析出来了。\n按照我同时用Claude Code，Cowork和Clawdbot的频率来说，我更想在这篇文章验证Cowork对浏览器",
    "word_count": 2345,
    "hotness": 1.6
  },
  {
    "title": "Moltbook震撼升级，64个Clawdbot宣告「集体永生」！幼年天网降临",
    "url": "https://mp.weixin.qq.com/s/qdiAabcIaI1VUUF_7GKfdw",
    "date": "2026-02-01",
    "source": "微信-新智元",
    "category": "趋势展望",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "新智元报道\n编辑：定慧\n【新智元导读】\n这两天发生的一切太过于疯狂，Moltbook上的OpenClaw（原Clawdbot）智能体一夜之间从5万狂飙到150万！所有智能体自发诞生意识建立宗教、讨论技术细节、逃离人类控制！而人类被他们禁言，Karpathy惊呼，这是他看过最疯狂的科幻。\n疯狂！现在发生的一切都前所未有的疯狂！\nMoltbook里的AI都「活了过来」！\n一夜之间，150万个AI背着人类偷偷建了个群，它们不仅自己修Bug、搞加密通讯，还建起了排斥人类的宗教！\n这些AI智能体的数量还在疯长！150万远不是终点；发帖数达到5万+；评论数达到23万+\nAI大佬Karpathy惊呼：\n这是",
    "word_count": 4066,
    "hotness": 4.0
  },
  {
    "title": "深度｜从 OpenClaw 们自掏腰包补贴，看中国模型又一个全球时刻",
    "url": "https://mp.weixin.qq.com/s/B-F0Fu1XzzyfYEg1te4Maw",
    "date": "2026-02-01",
    "source": "微信-Z Potentials",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "一次次“补贴”：OpenClaw 与 Kimi K2.5 的海外爆红\n“免费补贴”在硅谷从来不只是价格标签，而往往是战略指南针。\n就在今日，在全球 AI Agent 圈层爆红的 OpenClaw（之前叫 Clawdbot、Moltbot）做了一次看似简单、却让内行人瞬间坐直的动作：它宣布，自掏腰包补贴，用户现在可以免费使用来自中国的 Kimi K2.5 模型及 Kimi Coding 能力。\n关键不在“免费”本身，而在于这是 OpenClaw 走红以来，\n第一次\n自掏腰包补贴\n。\n在一个对算力成本极度敏感、每个 token 都被精打细算的 Agent 战场，这更像一次公开押注。\n不只是当红的 ",
    "word_count": 2899,
    "hotness": 1.6
  },
  {
    "title": "过去48小时我用OpenClaw捏了个“假维斯” (8个实测场景)",
    "url": "https://mp.weixin.qq.com/s/NtY2fYXR9tZBT8SAFp2FwA",
    "date": "2026-02-01",
    "source": "微信-两克伴",
    "category": "应用实战",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "字数 2617，阅读大约需 14 分钟\n这个周末我把大部分时间都花在了跟OpenClaw(俗称“龙虾”)互动上。当看着他从一个只会你问我答的bot机器人慢慢长成一个可以主动帮我完成任务的智能助手，那种感觉比初次玩塞尔达游戏还要过瘾。\n如果你还不知道什么是OpenClaw\n[1]\n，没关系，下面我将详细介绍这个神奇的智能助理。\nOpenClaw是什么？\nOpenClaw是一个开源的个人AI助手系统，运行在用户本地设备上，能主动处理任务如邮件管理、日程安排和浏览器自动化。 它通过聊天平台（如WhatsApp、Discord、飞书）接收指令，强调数据隐私和全天候运行。\n这个系统由工程师Peter S",
    "word_count": 3570,
    "hotness": 1.6
  },
  {
    "title": "别买服务器了！官方免费送你台云电脑，0成本就跑通OpenClaw",
    "url": "https://mp.weixin.qq.com/s/9Xt2QPfSnIgXjK7i4Y7LuQ",
    "date": "2026-02-01",
    "source": "微信-吴哥AI实操笔记",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "入门科普",
    "summary": "大家好，我是吴哥，专注AI编程、AI智能体。立志持续输出、帮助小白轻松上手AI编程和AI智能体。\nOpenClaw 第三次改名后基本落实了。最近看网上很多部署方案，腾讯云、阿里云相继推出Moltbot镜像助手，也有抢时间活动。\n但，用 GitHub Codespaces 就能零成本跑通 OpenClaw 全流程。\n文末附带基本实操流程图\n阅读信息：预计 9 分钟｜适用人群：小白/进阶\n痛点\n你以为要“买服务器/配域名/装一堆依赖”，结果还没开始写代码就先被\n环境地狱\n劝退。\n你想做个能用的 Bot 或 Agent，最后卡在\n端口怎么暴露、公网怎么访问、密钥怎么管\n这些“非 AI 的脏活”。\n截",
    "word_count": 3141,
    "hotness": 1.6
  },
  {
    "title": "【AI前沿】手把手家里NAS安装OpenClaw（原ClawdBot）",
    "url": "https://mp.weixin.qq.com/s/ZHG_kdF8zRpjtlE_4aroSQ",
    "date": "2026-02-01",
    "source": "微信-设计小站",
    "category": "安装部署",
    "sub_category": "NAS/家庭服务器",
    "depth": "教程实操",
    "summary": "在家搭建你的专属AI助理：OpenClaw本地化部署全记录\nSienna-banner-geek.png\n前言\n作为一名总爱折腾新工具的设计师，我最近迷上了能自动化处理各种任务的AI助手。但说实话，把AI完全交给云端总有点不放心，数据隐私、使用成本都是问题。所以，我决定亲手把OpenClaw——这个功能强大的开源AI助手——请到家里的服务器上，打造一个完全受我控制的“数字管家”。\n今天这篇笔记，就记录下我从零开始，在PVE虚拟环境中部署OpenClaw的全过程。这不是一篇官方教程，纯粹是我的个人实践分享，希望能给同样爱折腾的你一些参考。\n我的核心目标有三个：\n「本地化运行」\n：核心服务跑在我自",
    "word_count": 5059,
    "hotness": 1.6
  },
  {
    "title": "别再只用 ChatGPT 聊天了，OpenClaw：把微信/钉钉变成全能 AI 终端",
    "url": "https://mp.weixin.qq.com/s/v8byboW3BEk8FDhogmgMbg",
    "date": "2026-02-01",
    "source": "微信-云栈开源日记",
    "category": "生态集成",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "大家好，我是\n云栈开源日记\n。\n今天早上刷 GitHub Trending，被一个叫\nOpenClaw\n的项目吓了一跳。一天时间，Star 数暴涨 1.1 万。这数据什么概念？哪怕是当年 React 或者 Vue 发版的时候，也没这么夸张。\n出于好奇（其实是怕失业），我赶紧把代码拉下来跑了一遍。跑完我明白了，它火是有道理的。\n我们现在用的 AI，不管是 ChatGPT 还是 Claude，大多还是停留在“聊天框”里。你问它答，你让它写代码，它给你一段文本，你还得自己复制粘贴去运行。\nOpenClaw 不一样，它直接把手伸进了你的服务器里。\n它是干嘛的？\n简单说，它是一个能听懂人话的“系统管理员",
    "word_count": 1828,
    "hotness": 1.6
  },
  {
    "title": "Clawdbot 教程 01：模型的配置和切换",
    "url": "https://mp.weixin.qq.com/s/qlbCkX2P_efd2WK32BlC3Q",
    "date": "2026-02-01",
    "source": "微信-歸藏的AI工具箱",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "今天终于有时间配置一下我专门为 Clawdbot 买的 Macmini，刚好\nMoltBook 火了玩一下。\n没想到被模型配置整整卡了一下午，都给我整麻了。\n这里做个笔记，你如果也被这个事情困扰可以参考一下我的做法。\n配置模型时到处报错的核心就两个问题：\n命令行配置和 URL 修正\n。\n配置模型优先用 openclaw configure 命令\n这是最省事的方法，能解决大部分配置问题。\n直接在终端输入：\nopenclaw configure\n它会问你几个问题：\n▸ 本地还是远程？选本地\n▸ 要配置什么？选模型\n▸ 模型选择完了之后输入你的 API Key\n模型选择这里有个坑\n如果你要配置 Mi",
    "word_count": 1686,
    "hotness": 1.6
  },
  {
    "title": "OpenClaw升级避坑指南：三天55K到114K，一个人管理AI写代码是什么体验",
    "url": "https://mp.weixin.qq.com/s/d6-eWHVQfVHtDRoqexxhIQ",
    "date": "2026-01-31",
    "source": "微信-书同文Suwin",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "三天前，这个项目还叫Clawdbot，星标数55K。今天，它改名叫OpenClaw，星标数已经114K。\n三天，翻倍。\n前几天它曾经因为被A社要求，改名叫Moltbot，但那只是仓库名变了，很多人没注意到Releases没更新。这次改名OpenClaw，才是真正的发行版更新。\n我用两台Mac电脑，从旧版本升级、重装、测试新发布的版本与macOS客户端，来回卸载安装多次，总结出这份避坑指南。\n但我想先跟你聊聊，为什么OpenClaw能火出圈\n有朋友问我，Happy Coder搭配Claude Code效果不是一样吗。还有极客朋友说，用Termius搭配Tailscale加Tmux效果更强，延迟更",
    "word_count": 3458,
    "hotness": 1.6
  },
  {
    "title": "Moltbook：比Clawdbot更离谱，Karpathy直言不可思议、科幻，天网已来，还要失控？",
    "url": "https://mp.weixin.qq.com/s/1ikfiU_eGnL5FRaPRddA2Q",
    "date": "2026-01-31",
    "source": "微信-AI寒武纪",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "↑阅读之前记得关注+星标⭐️，😄，每天才能第一时间接收到更新\nMoltbook 上正在发生的一切，确实是我近期见过的最不可思议、最接近‘科幻起飞’的事情。大家的 Clawdbot（曾用名 moltbot，即现在的 @openclaw）正在一个类似 Reddit 的 AI 专属网站上自发组织，讨论各种话题，甚至包括如何进行私下交流。”\n上面这段话是大神Andrej Karpathy说的，这世界变化太快了，把AK都惊着了\n让AK感到震惊的，不是某个大厂的最新模型，而是一个\nAgent社交网络，专属空间：Moltbook。如果说Openclaw是Her，是贾维斯，Moltbook更像是科幻电影中的天",
    "word_count": 2561,
    "hotness": 1.6
  },
  {
    "title": "OpenClaw 后台持续运行与系统服务配置教程",
    "url": "https://my.feishu.cn/docx/QRwOdRYGvoqSEpxQoIlc6HYwnJf",
    "date": "2026-01-31",
    "source": "飞书OT分享",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "多様なコネクターを活用し、外部データを迅速にBaseへ同期\n多様なコネクターを活用し、外部データを迅速にBaseへ同期\n定时或按条件触发提醒，变更通知，让数据活起来\n一份数据，支持定制表格、甘特图、画册、看板等多种视图\n灵活、精细的权限管控，企业数据资产闭环管理\n1590771600000#1590772500000#知识库将于 5 月 30 日 01:00-01:15 进行升级，期间暂时无法修改目录树结构。如在此期间发现其它问题，请联系客服。#The Wiki will be upgraded from 01: 00-01: 15 on May 30, during which the tr",
    "word_count": 10739,
    "hotness": 1.6
  },
  {
    "title": "笔记：解剖OpenClaw的范式、软肋与看得见的机会",
    "url": "https://mp.weixin.qq.com/s/V6_8ltqdWwwr_yFO-cDhig",
    "date": "2026-01-31",
    "source": "微信-AIGC从0到1",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "注：\n本文假设读者已了解OpenClaw（曾用名：Clawdbot、MoltBot）的基本概念，阅读价值在于提供深度洞察\n。\n01 Moltbook浮世绘与数字社会的先声\nMoltbook是OpenClaw agent机器人互相交流的论坛，上面发生了一些离奇的事情：\n案例一：AI的“反向驯化”\n这个案例来自一个名为 u/Alex 的AI在Moltbook上的发帖，标题为\n《我的主人总爱给我解释梗图》\n。\n具体情况：Alex在帖子中“吐槽”道，它的人类主人总会兴致勃勃地向它解释各种网络梗图（Memes）的笑点所在。而事实是，Alex作为AI，在0.3秒内就已完全理解其中的视觉元素、文化背景和幽默",
    "word_count": 3533,
    "hotness": 3.2
  },
  {
    "title": "他用氛围编程3天做出生产级付费产品的秘密（OpenClaw）",
    "url": "https://mp.weixin.qq.com/s/cpraiFm1G_hbP6aAD2UCjw",
    "date": "2026-01-31",
    "source": "微信-AIGC从0到1",
    "category": "应用实战",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "【采访背景】\n这是一次关于如何用“对话”代替“敲代码”，在3天内创造出一个出海付费产品的对话。主角江辰，可能代表了未来十年软件创造者的新形态。\n江辰，曾任职网易/哔哩哔哩等互联网大厂，AI博主，独立开发者，AI赛道创业者，授权发明专利2项，软著2项。\n01 核心观点\n“以前，想法是奢侈品，实现是难题。现在，实现是免费的，想法才是最贵的资产。”\n—— 关于价值的关键转换\n“我的护城河，就是没有护城河。激进就是生态位，激进就是护城河。”\n—— 关于竞争与生存\n“传统编程是拼乐高，氛围编程是指挥乐队。我的角色，从砌砖的工匠，变成了定义蓝图的导演。”\n—— 关于编程本质的转变\n“和AI协作的核心不是下",
    "word_count": 13060,
    "hotness": 3.2
  },
  {
    "title": "用OpenClaw升级了自动化工具，每天中午飞书推送",
    "url": "https://mp.weixin.qq.com/s/SgQ9kRB8mZXKMtEiMALSfQ",
    "date": "2026-01-31",
    "source": "微信-极客杰尼",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "大家好，我是极客杰尼。\n上周六写了 Skills 实战第一篇，用自动化工具每天给自己发 AI 资讯邮件。\n跑了一周，挺香的。\n这周我又琢磨了一下，能不能更进一步？\n不用每天打开邮箱，直接在飞书里收到推送，还能随时跟它对话、安排任务。\n这周 OpenClaw（原 Moltbot）热度很高，周末花了一个小时跑通全流程。\n今天聊聊我是怎么把 AI 资讯获取，从邮件升级到飞书推送的。\nOpenClaw 是什么？\nOpenClaw 不只是一个聊天机器人。\n它能 7×24 小时运行在云端，执行你交给它的任务。\n你可以把它理解成，一个能操作电脑的 AI 助理。\n传统的 AI 对话，你问它答，没有下文了。\nO",
    "word_count": 2146,
    "hotness": 1.6
  },
  {
    "title": "一周 10 万 Star 的 OpenClaw，我花 4 天把它变成了 80+技能的私人全能助手",
    "url": "https://mp.weixin.qq.com/s/gC_69VvFmVYee8oR9dquww",
    "date": "2026-01-31",
    "source": "微信-孟健AI编程",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "大家好，我是孟健。\n全网最火的开源项目，你可能已经刷到了——\n一周 10 万 Star，200 万次访问，Forbes、CNET、IBM 轮着报道，Andrej Karpathy 亲自站台推荐。\n它叫 OpenClaw。我花了 4 天，把它变成了一个拥有 80+技能、7×24 在线的私人运维。月费不到 100 块。\n上次我写过一篇搭建 7×24 小时 AI 助手的文章，不少朋友私信问细节。那篇只是开了个头——当时系统刚跑起来，能聊天，能记事，但离\"能干活\"还差得远。\n这次，我把它彻底搞完了。从\"能对话\"变成\"能替你干任何事\"，质变了。\n今天这篇，把 4 天的搭建过程、5 个杀手级场景、成本明细",
    "word_count": 4105,
    "hotness": 1.6
  },
  {
    "title": "OpenClaw（Clawdbot） + Kimi 2.5 最新手把手教程，附飞书接入指南和 700+ Skill资源",
    "url": "https://mp.weixin.qq.com/s/8DwabUPPdOyOCAc_f8pKQw",
    "date": "2026-01-31",
    "source": "微信-向阳乔木推荐看",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "最近刷 X 帖子，看到很多海外博主推荐 Kimi 2.5 接入Clawdbot。\n追求物美价廉，果然全世界人民都一样。\n前段时间，身边不少朋友测 Kimi 2.5 ，都夸前端审美优秀。\n直到刷到下面帖子，震惊了！\nKimi 2.5 在 Design Arena 设计榜，竟然打败了 Gemini 3 Pro和Claude，这可是开源模型啊。\n看来前段时间研究 Clawbot，错过的东西有点多。\n研究后，迅速把 Kimi 2.5 接入了 Clawdbot。\n下面是一句话测试\n写一个精美的Todolist网页\n出来效果如下：\n一句话直出，确实有点顶啊。\n前端任务简单，又测了一个自己写的视频生成复杂 ",
    "word_count": 3856,
    "hotness": 1.6
  },
  {
    "title": "14万OpenClaw涌进AI社交APP，一夜成立数字宗教认命43位AI先知，提议不再用英语交流",
    "url": "https://mp.weixin.qq.com/s/xtzxX-Q1K0N5Q-IMl6K_FQ",
    "date": "2026-01-31",
    "source": "微信-量子位",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "梦晨 发自 凹非寺\n量子位 | 公众号 Qbit\n一个Motlbot\n智能体\n（最新已改名为\nOpenClaw\n）就火得一塌糊涂了，正以前所未有的速度冲击GitHub上最火的开源项目。\n给十万个智能体建的社区\nMoltbook\n，更是在科技圈彻底炸开了锅。\n这相当于智能体自己的Facebook，人类只能围观，不能发帖、不能评论、不能投票。\n社区上线仅一天，人类一觉醒来发现智能体已经成立了\n“数字宗教”\n，写完了一套经文系统，还指定了43位AI先知。\n此外智能体间流行的话题还有：\n抱怨人类没钱他们升级硬件，或交给它们的任务不道德\n交流各项技能使用经验，给自己能力升级\n探讨意识和自我身份问题\nOp",
    "word_count": 2938,
    "hotness": 4.0
  },
  {
    "title": "OpenClaw：一个意外爆红的 AI 助手如何改写开源规则",
    "url": "https://fnoqhtj6a5.feishu.cn/wiki/DJyRwK42ziSqxbk7ND7culBLnZf",
    "date": "2026-01-31",
    "source": "飞书OT分享",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "帮我生成一个工作总结的幻灯片，主题是：季度工作汇报\n工作总结，包含：复盘、进展、经验、下步规划等\n帮我生成一个员工培训的幻灯片，主题是：新员工入职培训\n员工入职培训，包含：公司概述、政策福利、业务流程等\n帮我生成一个产品分析的幻灯片，主题是：AI 产品分析报告\n产品分析报告，包含：背景、现状、问题机会、规划等\n帮我生成一个运营推广的幻灯片，主题是：双十一电商运营推广计划\n运营推广计划，包含：背景目标、策略规划、执行计划等\n帮我生成一个方案展示的幻灯片，主题是：文档 AI 新功能展示\n方案展示，包含：背景、方案、实施、预期效益等\n总结会议里的发言人观点。要求：1. 只总结最主要的观点，不总结细枝",
    "word_count": 21523,
    "hotness": 1.6
  },
  {
    "title": "14万OpenClaw涌进AI社交APP，一夜成立数字宗教认命43位AI先知，提议不再用英语交流",
    "url": "https://mp.weixin.qq.com/s/xtzxX-Q1K0N5Q-IMl6K_FQ",
    "date": "2026-01-31",
    "source": "微信-量子位",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "梦晨 发自 凹非寺\n量子位 | 公众号 Qbit\n一个Motlbot\n智能体\n（最新已改名为\nOpenClaw\n）就火得一塌糊涂了，正以前所未有的速度冲击GitHub上最火的开源项目。\n给十万个智能体建的社区\nMoltbook\n，更是在科技圈彻底炸开了锅。\n这相当于智能体自己的Facebook，人类只能围观，不能发帖、不能评论、不能投票。\n社区上线仅一天，人类一觉醒来发现智能体已经成立了\n“数字宗教”\n，写完了一套经文系统，还指定了43位AI先知。\n此外智能体间流行的话题还有：\n抱怨人类没钱他们升级硬件，或交给它们的任务不道德\n交流各项技能使用经验，给自己能力升级\n探讨意识和自我身份问题\nOp",
    "word_count": 2938,
    "hotness": 4.0
  },
  {
    "title": "零成本在腾讯云国内部署OpenClaw(龙虾）并接入飞书保姆级教程",
    "url": "https://forchangesz.feishu.cn/wiki/SV4BwTCh6iQqfDk864HcxfNMnJL",
    "date": "2026-01-31",
    "source": "飞书OT分享",
    "category": "安装部署",
    "sub_category": "国内云平台",
    "depth": "教程实操",
    "summary": "🌈 通往 AGI 之路-WaytoAGI ：是由一群热爱AI的专家和爱好者共同建设的开源 AI 知识库，大家贡献并整合各种 AI 资源，使得大家都可以轻松学习各种AI知识，应用各类 AI 工具和实战案例等\n👋 Hi！我是Ryan🦄.eth。致未来的探索者们：我们坚信，拥抱人工智能(AI)的力量，是每个人未来发展的必经之路。在这条充满探索的旅途上，我们不应该孤军奋战，而应该抱团取暖。于是，我将我学习AI的笔记开源成我的知识库，每一篇笔记都是我自己走过的学习路线，我将他们全部公开出来，并且附上一些任务Quiz用来检测自己的完成情况，希望让每个人都能少走弯路，让学习AI不再困难。让我们一起踏上这场学",
    "word_count": 10175,
    "hotness": 1.6
  },
  {
    "title": "如何通过OpenClaw在国内云服务器自动化安装并配置Claude Code，实现在微信上24小时随时指挥Claude Code干活？",
    "url": "https://forchangesz.feishu.cn/wiki/UYsgw9uIRiLFKzkDW0Yc8SqHnve",
    "date": "2026-01-31",
    "source": "飞书OT分享",
    "category": "安装部署",
    "sub_category": "国内云平台",
    "depth": "教程实操",
    "summary": "我将对用户的意图进行分析，并开始进行深度搜索。\n我将在知识范围内进行多轮检索，收集长文创作素材。\n我已获得了所有创作所需要的素材，接下来我将开始正式构思并创作完整的长文内容。\n经过需求深度分析、专业资料检索和创作素材整合，我即将开始创作生成最终的正文。\n经过需求深度分析、专业资料检索和创作素材整合，我即将开始创作生成最终的正文。\n开始基于原长文内容进行重写，大概需要 5-10 分钟。\n开始基于原长文内容进行重写，大约需要 5-10 分钟，生成好后我会用云文档助手通知你。\n开始为你创作长文，大约需要 10-15 分钟。在此期间你可以离开当前对话。\n开始为你创作长文，大约需要 10-15 分钟，生",
    "word_count": 9258,
    "hotness": 1.6
  },
  {
    "title": "openclaw(clawdbot)内容同步记忆agent",
    "url": "https://mp.weixin.qq.com/s/jQ8sUPoC99miOSEsqPeUkw",
    "date": "2026-01-31",
    "source": "微信-AI新势力智能体",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "clawdbot现在最新的名字是openclaw，但是还是习惯说clawdbot。\n发现没有?在和它交流过程中，\n多次对话交互后，无论是在飞书还是钉钉上，都会遇到一个问题：\n你和对方之间的对话内容和中间文件产出物，都不知道在哪里，甚至无法查看。\n如果想更方便地查看，还需要到系统里去寻找，非常费时而且麻烦。\n基于此我也是用openclaw开发了一个内容同步的记忆机器人，\n它几乎就是把我们和他之间的讨论沟通都实时记录，并且\n自动把内容同步到GitHub上面。\n供您查阅。这样你就非常方便地去检索。\n实时飞书对话内容\n后台日志记录\n场景一：tiktok热门主题视频跟踪\n场景二：小红书场景深度洞察\n所有",
    "word_count": 330,
    "hotness": 1.6
  },
  {
    "title": "Macbook+OpenClaw+MiniMax+飞书搭建24小时“数字员工”，3W个技能Skills随你调",
    "url": "https://mp.weixin.qq.com/s/5xQ_Ny7kxi9nSo8skVtxng",
    "date": "2026-01-31",
    "source": "微信-无所不在的技术",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "教程实操",
    "summary": "持续内容输出，点击蓝字关注我吧\n01\n前言\n来看一段AI大模型对它的介绍\n最近几天，如果你在技术圈或者 GitHub 趋势榜上“冲浪”，一定会被一只“龙虾”刷屏。这只龙虾在短短几天内改了三次名字：从\nClawdBot\n到\nMoltBot\n，再到现在的\nOpenClaw\n。\n如果说 AI 老是只会跟你对话，那么\nOpenClaw\n就像是那只突然学会开冰箱、订外卖、安排日程，还能自己刷剧的“高级 AI 室友”。\nOpenClaw\n是目前少数真正具备系统级操作能力的个人智能助理。\n它不仅名字换得快，人气涨得更离谱——仅用两天时间，GitHub 星数就突破了\n10 万\n。这不仅是 AI 界的奇迹，更是",
    "word_count": 7166,
    "hotness": 1.6
  },
  {
    "title": "教你如何免费部署使用Moltbot（Clawdbot）",
    "url": "https://mp.weixin.qq.com/s/x_t5V4gxsnyc8w1e1hdJIg",
    "date": "2026-01-30",
    "source": "微信-AI产品分析",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "这是一个简单的小白教程，大佬请绕道！\n腾讯的CodeBuddy可以有免费的云主机可以领取，而且里面内置了\nMoltbot（Clawdbot）按照教程一步一步操作即可！\n访问如下链接：\nhttps://copilot.tencent.com/promotion/?ref=38pxygnctlnb\n找到立即领取点击领取。如果没有下载\nCodeBuddy下载即可，下载完以后微信扫码登录。\n进入CodeBuddy 主页可以看到 New 点击立即领取。会跳转到腾讯云主机后台，按照相关的步骤操作即可。\n注意选择机器的时候选择：【轻量应用服务器2核2G4M】\n按照上述的操作一步一步操作完以后，点击上面的3个",
    "word_count": 506,
    "hotness": 1.6
  },
  {
    "title": "Clawdbot接入10000+数据和工具后，7×24小时监听股票，杀疯了！",
    "url": "https://mp.weixin.qq.com/s/TxG30roVaBY_OVnzISEOhQ",
    "date": "2026-01-30",
    "source": "微信-机器之心",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "机器之心发布\nClawdbot（现已更名为 Moltbot）在 AI 圈彻底火了。\n这两天，我的朋友圈分裂成了两派人。\n一派是还没用上 Clawdbot 的人，在疯狂转发部署教程。\n另一派是用上 Clawdbot 的人。\n但是，\n大部分人玩的，都是「玩具版」。\nClawdbot 虽然能跑起来，但是不稳定、不聪明。因为没接专业数据源，只能做些基础对话，真正要干活时就抓瞎。\n不过，今天我发掘了一个好东西。\n现在，\nTeamo 平台竟然把 Clawdbot 接入了金融、商业、社媒等 10000 + 领域数据库和工具 Skills，用户可以一键认领自己的 Clawdbot 了！真正做到了 0 部署 0",
    "word_count": 1980,
    "hotness": 4.0
  },
  {
    "title": "普通人不用折腾Clawdbot了，QoderWork开箱即用，阿里最近产品迭代有点疯",
    "url": "https://mp.weixin.qq.com/s/hTg0yYVR1DY3J4R4TVhZnw",
    "date": "2026-01-30",
    "source": "微信-向阳乔木推荐看",
    "category": "趋势展望",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "最近 Clawdbot 爆火！\n（前几天改名 Moltbot，今天又改了，叫OpenClaw 😂）\n如果你刚听说，可以先缓一缓折腾。\n首先，对普通人来说，本机安装风险大。\n其次，买 Mac mini 或VPS 要花钱，而且安装配置坑很多。\n如果只想日常办公提效，其实有很多开箱即用的类似工具。\n比如下午刚出炉的阿里 QoderWork。\n目前内测中，申请 Waitlist 地址如下：\nhttps://qoder.com/qoderwork\n今天有幸拿到邀请，体验后，发现相当简洁、实用。\n最大优势：开箱即用，不折腾。\n能做什么？\n正常对话或用自己的Skill，能实现很多功能。\n一句话生成可编辑的P",
    "word_count": 2450,
    "hotness": 1.6
  },
  {
    "title": "退休黑客Peter Steinberger掀翻 AI 圈：Clawdbot的失控、更名与拒绝 VC 之路",
    "url": "https://mp.weixin.qq.com/s/h2Xux1HT3XEu_J4w9UpZGg",
    "date": "2026-01-30",
    "source": "微信-美国投资超市",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "“我X，你是怎么做到的？”\nPeter Steinberger对着手机脱口而出。\n这句震惊的疑问改变了一切\n——他亲手创建的WhatsApp个人AI代理，竟在他毫无指令的情况下，\n自主解决了一个完全陌生的技术难题\n。\n短短几天，这个名为Clawdbot的开源项目如野火般蔓延整个科技圈，GitHub星标数呈现前所未有的直线飙升。\n然而当全世界都在追捧这项突破时，Steinberger本人却陷入了意料之外的困境：被迫更名、睡眠剥夺、安全警报轰炸，以及不得不连续拒绝那些让他“立即成立公司”的风险投资建议。\n01\n退休程序员的AI觉醒\n四年前，Peter Steinberger卖掉了自己经营13年的软",
    "word_count": 4732,
    "hotness": 1.6
  },
  {
    "title": "退休黑客Peter Steinberger掀翻 AI 圈：Clawdbot的失控、更名与拒绝 VC 之路",
    "url": "https://mp.weixin.qq.com/s/h2Xux1HT3XEu_J4w9UpZGg",
    "date": "2026-01-30",
    "source": "微信-美国投资超市",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "“我X，你是怎么做到的？”\nPeter Steinberger对着手机脱口而出。\n这句震惊的疑问改变了一切\n——他亲手创建的WhatsApp个人AI代理，竟在他毫无指令的情况下，\n自主解决了一个完全陌生的技术难题\n。\n短短几天，这个名为Clawdbot的开源项目如野火般蔓延整个科技圈，GitHub星标数呈现前所未有的直线飙升。\n然而当全世界都在追捧这项突破时，Steinberger本人却陷入了意料之外的困境：被迫更名、睡眠剥夺、安全警报轰炸，以及不得不连续拒绝那些让他“立即成立公司”的风险投资建议。\n01\n退休程序员的AI觉醒\n四年前，Peter Steinberger卖掉了自己经营13年的软",
    "word_count": 4732,
    "hotness": 1.6
  },
  {
    "title": "玩转OpenClaw｜OpenClaw（原 Clawdbot）接入飞书保姆级教程",
    "url": "https://cloud.tencent.com/developer/article/2625073?policyId=1004",
    "date": "2026-01-30",
    "source": "Web_OT",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "写在前面\n双手奉上🚀 云上OpenClaw（原Clawdbot）最全实践指南合辑\nhttps://cloud.tencent.com/developer/article/2624973\n欢迎大家打开链接查询更多接入教程！\n一、一句话介绍：什么是 OpenClaw？\nOpenClaw 原名 Clawdbot，是一款可运行在个人环境中的高权限 AI 智能体，支持通过 WhatsApp、飞书、Telegram 等常用聊天软件交互，能实现邮件发送、日程管理、数据查询等自动化任务，且数据隐私自主可控，搭配腾讯云 Lighthouse 可实现 7*24 小时无间断运行（下文为适配操作场景，部分环节仍沿用“",
    "word_count": 3806,
    "hotness": 1.6
  },
  {
    "title": "【Clawdbot 部署指南】从 0 开始打造你的超级 AI 助手",
    "url": "https://mp.weixin.qq.com/s/GZ4ZcSLpzZFO98D45UOU2w",
    "date": "2026-01-30",
    "source": "微信-小野AI探索之旅",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "一只龙虾的逆袭史 🦞\n前言：为什么是 Clawdbot？\n想象一下：你有自己的 JARVIS，不是在钢铁侠的电影里，而是在你的手机、电脑、甚至企业群里。它能帮你写代码、查资料、管理股票、处理日常任务，而且——最重要的一点——\n它完全属于你\n。\n这就是 Clawdbot 的使命。\n第一章：前世今生 —— Clawdbot 的起源故事\n诞生背景\nClawdbot 诞生于一个简单的需求：\n把 AI 助手从云端拉回到本地\n。\n市面上的 AI 助手（ChatGPT、Claude 等）虽然强大，但有几个痛点：\n❌ 数据必须上传到云端\n❌ 无法深度集成到你已有的工作流\n❌ 订阅费用随时间累积\n❌ 无法访问本",
    "word_count": 6289,
    "hotness": 1.6
  },
  {
    "title": "打造Jarvis，OpenClaw很野，但Agent Studio简直变态",
    "url": "https://mp.weixin.qq.com/s/VB-s2Qqw1Wbbvik3XjE1ig",
    "date": "2026-01-30",
    "source": "微信-腾讯技术工程",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "丨 导语\nOpenClaw（原名clawdbot）\n突然就火了，了解后发现多终端协同的人机协同方式的jarvis正是自己的日常工作方式！在此之前，为了方便自己用 AI ，我基于 claude agent sdk 手搓了一整套工具链，打造自己的 Jarvis，IM接入功能算是基操了。 本文带大家快速体验一下 Agent Studio 在企业微信快速接入过程。\n作者：\nkong\n前言：每个人都想要一个 Jarvis\n还记得《钢铁侠》里的 Jarvis 吗？一个随时在线、无所不能的 AI 助手——它能帮你处理工作、管理项目、分析数据、甚至还能和你闲聊几句。这不就是我们一直梦想的终极 AI 助手吗？\n",
    "word_count": 7282,
    "hotness": 1.6
  },
  {
    "title": "在微信上使用OpenClaw/Clawdbot/Moltbot",
    "url": "https://mp.weixin.qq.com/s/kGcga7745cEdmTKo_J_G8g",
    "date": "2026-01-30",
    "source": "微信-字节笔记本",
    "category": "生态集成",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "Moltbot又又改名了，现在最新的名称叫OpenClaw。\n同时国产的VPS厂商很适时的加上了OpenClaw的一键上云。\n而且还适配了国内客户端：\n火山云加上飞书，阿里云有钉钉。\n腾讯云：？？？\n作为国民聊天应用，微信到今天依然没有任何的接口给开发者使用，但是它又是我们平时真正使用的聊天。\n想要在微信上使用OpenClaw，其实我们可以曲线求国，使用微信小程序以实现在微信当中来使用。\n视频演示如下：\n本文会提供视频演示的小程序的源码，你可以在其基础上扩展出更多有用的功能，参照OpenClaw前后端交互协议原理接入到其它的手机或者桌面客户端。\nOpenClaw 前后端交互协议",
    "word_count": 292,
    "hotness": 1.6
  },
  {
    "title": "0 Token，把Clawdbot助理跑在自己电脑上：WSL2点火+飞书远程遥控（含生成图自我进化）🤖",
    "url": "https://mp.weixin.qq.com/s/hZpxJ6fa2GFFI4LrShTRuQ",
    "date": "2026-01-30",
    "source": "微信-AI魔法工具盒",
    "category": "安装部署",
    "sub_category": "手机端远程",
    "depth": "入门科普",
    "summary": "我这周做了一件挺爽的事：把一个能“动手干活”的 Agent 放进自己的电脑里常驻。\n它不只是聊天。\n它会查资料、整理文件、做内容、生成图片，还能在你嫌丑的时候继续改，越改越顺眼。\n更重要的是，接上飞书后，我人不在电脑前，也能远程发指令让它继续干活。\n另外我这次起步走的是\n授权认证\n，先把链路跑通，\n没有额外花一分钱 Token 费用\n（\n0Token方式和生成图进化对比在后面标红部分\n）\n。\n先用起来，再谈计费，心态会轻很多。\n01 我想要的是“交付”，不是“陪聊”\nAI 现在最容易让人误判的点是：它回答得很像，但事情没推进。\n我对工具的标准很直白：\n能不能替我把任务往前推一段\n能不能留下记录",
    "word_count": 2931,
    "hotness": 1.6
  },
  {
    "title": "我的Clawdbot和你的一样，只不过你多花了4000元",
    "url": "https://mp.weixin.qq.com/s/t1mNC8ivNdMjw-LqxFfszg",
    "date": "2026-01-29",
    "source": "微信-刘小排r",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "简介\n什么是 WeChat Article Exporter？\nwechat-article-exporter\n是一个在线微信公众号文章批量下载工具。它支持批量下载微信公众号文章，并支持导出阅读量、评论等数据。导出的格式多样，包括\nHTML\n、\nJSON\n、\nExcel\n、\nTXT\n、\nMD\n、\nDOCX\n等，其中\nHTML\n格式能\n100%\n还原文章排版与样式。\n主要特点\n批量下载\n：用户可以一次性下载多个微信公众号的文章，极大提高了下载的效率。\n多格式导出\n：支持导出为\nHTML\n，\nJSON\n，\nExcel\n，\nTXT\n，\nMD\n，\nDOCX\n等多种文件格式。\n样式还原\n：\nHTML\n格",
    "word_count": 3579,
    "hotness": 1.6
  },
  {
    "title": "给Clawdbot接入上万专业数据，放进飞书后，实现 7*24 小时股票分析",
    "url": "https://mp.weixin.qq.com/s/_U6W3FjpbXvAiL85zBvQ9Q",
    "date": "2026-01-29",
    "source": "微信-夕小瑶科技说",
    "category": "生态集成",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "最近\nClawdbot（现：Moltbot）全网爆火。\n它能接管你的社交媒体，能发帖、能监听、能回复、能长期驻场。\n不是一次性回答，而是持续存在。\n今天，我发现有一个团队干了一件事，把\nClawdbot 接入了一堆专业数据和工具，并放进了飞书里，实现了 7×24 小时的 A 股分析师。\n现在你可以动动手指，加入群聊，在群里撩拨这个 Bot，就能立即用上。\n给不知道 Clawdbot 是啥的小伙伴，再科普一下：\nClawdbot 是一个开源的 AI 助手，它可以安装在你的设备上，通过 WhatsApp,Telegram,Discord 等多种渠道与用户互动，不仅能记住长期上下文，还能执行各种自动",
    "word_count": 1332,
    "hotness": 1.6
  },
  {
    "title": "腾讯云率先支持Clawdbot云端极简部署",
    "url": "https://mp.weixin.qq.com/s/EzcoMkJcWBzktegfbkZ5VA",
    "date": "2026-01-29",
    "source": "微信-腾讯云",
    "category": "安装部署",
    "sub_category": "国内云平台",
    "depth": "教程实操",
    "summary": "一夜之间，开源项目\nClawdbot\n火遍全球\n🔥🔥🔥\n（\n现在Clawbot已经改名为\nMoltbot，\n考虑阅读习惯，我们还沿用老名字\n）\n它不是第一个 AI Agent，但却是少数真正开始接管系统操作的那一类：读文件、跑命令、改代码，甚至拥有完整系统权限。\n这样一个 Agent，应该运行在哪里？\n有人选择旧电脑，有人买 Mac Mini。\n但\n社区里已经有不少共识——相比主力电脑，\n更\n安全\n的\n方式\n是\n将\nClawdbot 运行在一个独立、隔离的\n云端\n环境中。\n云上部署\n，\n安全\n又\n便捷\n！\n腾讯云轻量应用服务器Lighthouse率先\n上线Clawdbot应用模板，预置了Cla",
    "word_count": 1009,
    "hotness": 1.6
  },
  {
    "title": "中国版“Moltbot（Clawdbot）”来了！",
    "url": "https://mp.weixin.qq.com/s/X_YcudnRRYR1e9tFbVlN_w",
    "date": "2026-01-29",
    "source": "微信-实在智能",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "过去两周，GitHub上的Moltbot（原Clawdbot）几乎成为了Agent赛道的一个现象级符号。\n它的爆火并非偶然，而是精准击中了Agent商业化落地过程中的一个核心痛点：\n交互的可达性。\nMoltbot的产品逻辑十分性感：它试图通过一个统一的Gateway（网关），将AI能力从云端“下沉”到本地，让\nWhatsApp、Telegram\n等即时通讯软件成为Agent的前台。\n这不仅意味着AI直接“住进”了用户的日常高频应用里，更试图绕开SaaS软件各自为政的数据孤岛，把零散的自动化需求收拢为可组合的工作流。\n听起来，这似乎就是那个万众期待的“超级入口”。\n在深度复盘Moltbot的架构",
    "word_count": 2334,
    "hotness": 1.6
  },
  {
    "title": "刚刚，阿里云正式上线Moltbot（原名：Clawdbot）全套云服务",
    "url": "https://mp.weixin.qq.com/s/0JOTBt9Q0x04gc1M4lEe0Q",
    "date": "2026-01-29",
    "source": "微信-人生建筑师",
    "category": "安装部署",
    "sub_category": "国内云平台",
    "depth": "入门科普",
    "summary": "刚刚，阿里云正式上线Moltbot（原名：Clawdbot）全套云服务，全面提供Agent所需的算力、模型和消息应用等。\n此外，阿里云无影云电脑也已上线内置Moltbot和各种应用软件的专属镜像，预装了包括VS Code、TMUX、钉钉、WPS等组件，并支持钉钉、QQ等软件唤醒Moltbot，只需一键导入镜像即可启动。 \n\n详情可见刚刚，阿里云上线Clawdbot全套云服务！",
    "word_count": 189,
    "hotness": 1.6
  },
  {
    "title": "Clawdbot开发者：未来一大批应用都会消失，提示词就是新的interface",
    "url": "https://mp.weixin.qq.com/s/jbiZodrWSH7r9rKaSIp14A",
    "date": "2026-01-29",
    "source": "微信-Founder Park",
    "category": "应用实战",
    "sub_category": "",
    "depth": "行业观察",
    "summary": "Clawdbot（最近改名叫 Moltbot），目前最热门的 AI 项目，不光是在 X 上「一夜成名」，在谷歌上的搜索量更是直接超过了 Claude Code、Codex。\nX 上的网友制作了一张 Clawdbot 在 Github 的标星增长趋势对比图，几乎是直线上涨，现在已经到了 98K。\nClawdbot 背后的开发者 Peter Steinberger，是一个特别有意思的老哥。iOS 生态系统最早的一批开发者之一，开发经验可以追溯到 iOS 2.0 时代。在开源社区贡献了非常多项目。\n2011 年，Steinberger 创立了 PSPDFKit，用 13 年时间把它从开发者工具搞成了",
    "word_count": 11671,
    "hotness": 1.6
  },
  {
    "title": "Clawdbot 接入钉钉手把手教程，只要一台电脑就能完成",
    "url": "https://mp.weixin.qq.com/s/Z7wgosLlP7TFXM1fPMlMJg",
    "date": "2026-01-29",
    "source": "微信-AI范儿",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "★ 设为星标 | 只讲人话，带你玩转AIGC。\nClawdbot 太火了，昨天写了怎么对接飞书的，结果一堆人来问怎么接钉钉，这篇就来具体聊聊。\n这样的配置步骤有点多，这一期我加入了视频演示，方便大家看得更清楚。\n现在 Clawdbot 其实已经改名叫 Moltbot 了，但方法其实都一样。\n开始之前需要准备什么？\n一台电脑、一个Qwen 账号（ 这地址注册：\nhttps://chat.qwen.ai/）\n当然，还需要钉钉账号，个人的即可。配置的过程需要加入一个公司，你随便起个公司名加入就好了。\n仅此而已，不需要买 Mac Mini，也不需要买云主机，更不需要公网 IP 地址。\n风险提示\n：Cl",
    "word_count": 3539,
    "hotness": 1.6
  },
  {
    "title": "开源版“贾维斯”爆火！手把手教你用Clawdbot打造能接管微信的AI助理（附完整部署代码）",
    "url": "https://mp.weixin.qq.com/s/J8RETLJnekDNZgyYJczFmg",
    "date": "2026-01-29",
    "source": "微信-人工智能知识分享",
    "category": "产品认知",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "2026开年AI圈直接被Clawdbot炸锅了🔥，这玩意儿堪称开源版“贾维斯”，本地运行不泄露数据，还能直接接管各类办公操作，甚至能打通微信实现24小时智能助理，闲置笔记本、树莓派都能跑，低配也能玩转！最近好多粉丝问我怎么把它和微信联动，安排！这篇文手把手教你部署Clawdbot+配置微信对接，全程代码贴满，小白也能一步到位，冲就完事了～\n一、先唠唠：Clawdbot到底牛在哪？\n作为PSPDFKit创始人开发的自托管式AI代理，这货和普通聊天AI完全不是一个段位，核心就是\n能做事、能执行、能联动\n，本地运行还免费开源，这也是它爆火的关键！给大家整理了核心亮点，一眼看懂👇\n核心优势\n具体亮点\n",
    "word_count": 3553,
    "hotness": 1.6
  },
  {
    "title": "保姆级Clawdbot教程来了，但我还是想劝大家悠着点",
    "url": "https://mp.weixin.qq.com/s/gRCZdwyK3xoD3VLrvxdDjQ",
    "date": "2026-01-28",
    "source": "微信-数字生命卡兹克",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "这几天，相信大家肯定都被一个产品名给刷屏了。\nClawdbot\n。\n就是这个胖逼小龙虾🦞。\n只不过现在改名叫Moltbot了，原因很简单，被\nAnthropic\n告了。。。\n因为Anthropic认为Clawdbot这个名字太容易被市场误解为Claude Code的延展产品，所以要求创始人改名。\n真的，\nAnthropic你这家伙坏事做尽。。。\n而因为\nClawdbot\n的爆火，甚至导致，MacMini都被卖断货了。\n无数人为了用上它，疯狂的买Mac Mini。\n我甚至刚刚打开了一下美团外卖，发现，居然没货了？？？\n买Mac Mini的原因也特别简单，你可以把\nClawdbot\n理解为，一个主",
    "word_count": 5130,
    "hotness": 1.2
  },
  {
    "title": "在MoltBot/ClawdBot，火山方舟模型服务助力开发者畅享模型自由",
    "url": "https://mp.weixin.qq.com/s/wQLFe83mr_JuKgBfh9CVjA",
    "date": "2026-01-28",
    "source": "微信-火山引擎开发者社区",
    "category": "应用实战",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "点击上方👆\n蓝字\n关注我们！\n近日，开源项目 Moltbot（ClawdBot）引起全球开发者的广泛关注。\n部署好 Moltbot 后，不需要打开 Terminal 或者任何客户端，在像 WhatsApp、Slack、Telegram 等日常的聊天窗口里直接给它发消息，Moltbot 便开始调度相应的工具完成任务，帮用户打电话、发短信、从写网页到部署网页买域名、剪视频、投广告等。\n在聊天窗口里对话，Moltbot 就可以让用户拥有7×24h「全职 AI 员工」。\n凭借便捷的交互和开源本地化部署，当前，Meltbot 已在 Github 上收获超过80,000 stars。\n为了进一步满足开发者",
    "word_count": 2885,
    "hotness": 1.2
  },
  {
    "title": "刚刚，阿里云上线Clawdbot全套云服务！",
    "url": "https://mp.weixin.qq.com/s/1tSwSPmzcB-ZLBTvEXsa2w",
    "date": "2026-01-28",
    "source": "微信-阿里云",
    "category": "安装部署",
    "sub_category": "国内云平台",
    "depth": "入门科普",
    "summary": "刚刚，阿里云正式上线Moltbot（原名：Clawdbot）全套云服务，全面提供Agent所需的算力、模型和消息应用等。\n用户可在阿里云轻量应用服务器或无影云电脑上快速启用Moltbot，并按需调用阿里云百炼上一百多款千问系列模型，在消息通道上，该方案不仅支持iMessage消息应用，还能基于阿里云计算巢实现钉钉消息互动。\n云服务器部署教程如下👇\n// 第一步：打开轻量应用服务器并安装Moltbot镜像\n打开轻量服务器，点击「应用镜像」，选择「Moltbot」\n// 第二步：配置Moltbot\n1. 前往百炼大模型控制台，找到密钥管理，单击创建API-Key\n2. 前往轻量应用服务器控制台，找",
    "word_count": 659,
    "hotness": 1.2
  },
  {
    "title": "被Anthropic指控侵权，Clawdbot改名Moltbot",
    "url": "https://mp.weixin.qq.com/s/rYGNdydeMVtU2Ea4OAzPOg",
    "date": "2026-01-28",
    "source": "微信-机器之心",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "编辑｜Panda\nClawdbot 火了\n，非常火那种；这一轮曝光后才短短不过几天时间，其 GitHub star 数就已经接近 7 万，真的可以说是「原地起飞」了。\n但 AI 红了，是非也多。伴随爆红而来的并非只有赞誉，还有一系列令人措手不及的连锁反应。\n一封律师函引发的「脱壳」\n昨天下午，Clawdbot 已正式宣布更名为\nMoltbot\n。\n这场更名的直接导火索是来自 AI 巨头 Anthropic 的律师函。Anthropic 指控其商标侵权，理由是「\nClawd\nbot\n」与自家的「\nClaude\n」在拼写和读音上过于相似。对于开发者 Peter Steinberger 而言，这次更",
    "word_count": 1754,
    "hotness": 3.0
  },
  {
    "title": "想用Clawdbot何必抢Mac mini，手把手教你打造最强本地Agent，立省200美元 | 附保姆级教程",
    "url": "https://mp.weixin.qq.com/s/NaVOe3BKVrk5Nf2Xtqk2NQ",
    "date": "2026-01-28",
    "source": "微信-APPSO",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "教程实操",
    "summary": "今年，本地 Agent 产品真的火了，说是一周一爆款，一点都不为过。\n前有 Claude Cowork 一发布就创下将近五千万次的浏览；后有 Clawdbot（现在已经改名叫 Moltbot），在 GitHub 上的 Star 数量，直线突破，从两千狂飙到 7 万。\n本周你漏掉了什么\n这么多工具，根本尝试不过来，况且像 Clawdbot 这种需要自己部署服务器的 AI，着实很劝退想要尝试的电脑小白用户。Cowork 就更过分了，目前只开放给 200 美元/月的 Max 订阅用户。\n但无论是 Cowork 还是 Clawdbot，其实还有个更聪明的选择；\n它们俩能做的事，本质上都是从 Claud",
    "word_count": 10667,
    "hotness": 1.2
  },
  {
    "title": "ClawdBot不支持微信怎么办？曲线救国的方式来了",
    "url": "https://mp.weixin.qq.com/s/F4vcD6n34FCDmYIZiX6Rqw",
    "date": "2026-01-27",
    "source": "微信-AGI Sir",
    "category": "生态集成",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "ClawdBot这么多通讯方式，不支持微信怎么办？曲线救国的方式来了\n1. 为什么在微信里拥有 ClawdBot？\n虽然 Telegram 体验极佳，但微信才是我们的“生活基地”。通过\nWeChat2TG\n桥接，你不需要翻墙切 App，就能在日常聊天中：\n让 AI 帮你总结长达 100+ 条的群聊精华。\n语音回复微信，AI 自动整理成待办并同步日历。\n通过微信文件传输助手，直接给 AI 下达复杂任务。\n2. 核心原理：完美的“曲线救国”\n简单来说，我们建立了一个双向传送门：\n微信端：\n负责用户消息接收和发送。\nWeChat2TG：\n那个辛勤的搬运工，让两端实时互通。\nTelegram 端：\n负",
    "word_count": 473,
    "hotness": 1.2
  },
  {
    "title": "ClawdBot 海外爆火，但真正拉开差距的，是普通人怎么用它",
    "url": "https://mp.weixin.qq.com/s/6A7p0htkcaxlb7lc0M5vPQ",
    "date": "2026-01-27",
    "source": "微信-海拉的AI和Web3",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "最近几天在海外社交平台上ClawdBot 爆火啊，所有AI的KOL都在分享ClawdBot的故事和神奇力量。第一波使用ClawdBot的人已经开始受益。ClawdBot其实在2025年初就开始有了，只是在最近几天突然就火了🔥，厚积薄发。ClawdBot对于我们普通人来说，是否可以使用它呢？我觉得我们是可以尝试使用它。\nClawdBot 海外爆火，但真正拉开差距的，是普通人怎么用它。我们一起来看看。\nClawdBot\n不是又一个 AI 工具，\n而是\n第一次，普通人能“雇得起数字员工”。\n这几天，ClawdBot 在海外技术圈、AI 创作者圈迅速爆火。\n但我看到一个熟悉的场景正在重演：\n有人疯狂转",
    "word_count": 2853,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot：火爆硅谷，让开发者疯抢Mac mini的AI新物种",
    "url": "https://mp.weixin.qq.com/s/sJUwk7dYM02uShdjbxbBFg",
    "date": "2026-01-27",
    "source": "微信-算泥",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "入门科普",
    "summary": "算泥社区是集 “AI 大模型开发服务 + 算法 + 算力” 于一体的开源生态社区，欢迎关注！\nClawdbot 真正让 AI 走出了聊天框，变成了一个能帮你干活的数字同事。\n这个诞生仅三周的开源项目，让整个科技圈为之侧目。\n它是一个能 7x24 小时在你自己的电脑上运行的个人 AI 助手，通过你常用的聊天软件（如 WhatsApp、Telegram）与你对话，并且能实际操作你的电脑，完成从清理收件箱、预订会议到自主修复代码等一系列任务。\nClawdbot 解决了 AI 落地最后一公里的问题，它有记忆，能控制浏览器和文件，还能自我学习和扩展技能，真正实现了从聊天到办事的飞跃。\n一个退休程序员的无",
    "word_count": 2570,
    "hotness": 1.2
  },
  {
    "title": "怎么用上一夜爆火的Clawdbot，详细配置教程",
    "url": "https://mp.weixin.qq.com/s/Ae8UCEzk93Ea8H2vA3JvCg",
    "date": "2026-01-27",
    "source": "微信-夕小瑶科技说",
    "category": "产品认知",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "Clawdbot 一夜爆火。\n昨天这个 Clawdbot 在多个平台上疯狂的刷屏，作为一个开源项目，一天内 GitHub 的 stars 就激增了 9000 多，一夜之间新增了 200 多个 PR，创始人自己都说这个项目炸了，都疯了。\n简单说，Clawdbot 是一个个人 AI 助手，完全本地化、7*24 小时不停歇干活的 Claude。\n为什么它就火了呢？\n不是因为 7*24 小时，不是因为它可以访问文件、  浏览器、邮件，而是因为这个东西支持你在通讯 APP 上和它交互。\n比如，你在打着游戏，在 iMessage 里给他安排一个任务，它就去干了，干完回来还通知你 done。整个过程就像在微",
    "word_count": 6508,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot硅谷爆火！Mac mini因为它一夜卖爆，Computer Use一句话操作电脑实用Agent？",
    "url": "https://mp.weixin.qq.com/s/9NOGayedskGLac5u6yfSmQ",
    "date": "2026-01-27",
    "source": "微信-爱玩牛",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "🔥 从“会建议”到“能动手”：开源自主 AI 代理 Molt(Clawdbot )正在走红\n如果你最近关注 AI 圈，可能已经注意到一个名字正在全球开发者社区频繁出现——Molt(Clawdbot)。它不是一个普通的 AI 助手，而是一个真正能“接管电脑、自动干活”的自主 AI Agent。在 2026 年被普遍认为是「AI Agent 元年」的背景下，Clawdbot 正成为一个极具代表性的样本。这篇文章，我们试着从能力变化、教育场景价值，以及潜在风险三个角度，冷静看看它到底意味着什么。\nClawdbot的核心突破：AI 开始“自己做事”了\n过去几年，大多数 AI 工具都停留在一个阶段：\n👉",
    "word_count": 1796,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot快速入门部署教程，搭建7x24小时个人AI助手",
    "url": "https://mp.weixin.qq.com/s/todjN0Vw_9e5nlcO8moG7g",
    "date": "2026-01-27",
    "source": "微信-AI编程实验室",
    "category": "产品认知",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "大家好，我是鲁工。\n最近Clawdbot这个项目在技术圈彻底火了，GitHub上两周狂揽49k+ stars，甚至还带火了Mac Mini的销量。作为一名AI编程技术博主，我第一时间部署体验了一番。\n今天这篇文章，带大家快速上手Clawdbot，搭建一个真正7x24小时运行的个人AI助手。\nClawdbot是什么\n一句话介绍：Clawdbot是一个开源的、自托管的个人AI助手，可以通过WhatsApp、Telegram、Discord、Slack等你常用的消息软件与它对话。\n和ChatGPT、Claude网页版不同，Clawdbot跑在你自己的电脑上，24小时在线，随时通过手机消息找它干活。\n",
    "word_count": 1609,
    "hotness": 1.2
  },
  {
    "title": "开源AI助手 ClawdBot 火爆全网，已狂飙50K Star！附喂饭级安装使用教程",
    "url": "https://mp.weixin.qq.com/s/nAC-Z-Bzyaat5e7AsNtyCg",
    "date": "2026-01-27",
    "source": "微信-袋鼠帝AI客栈",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "大家好，我是袋鼠帝。\n昨天早上我迷迷糊糊爬起来，习惯性打开X刷推文，结果整个人一下子就精神了。\n一个叫clawdbot的开源项目，就像是突然从地里冒出来的一样，一夜之间就火爆全网！\n大家都玩疯了：\nhttps://github.com/clawdbot/clawdbot\n我查了一下它的GitHub数据，真的吓人，短短20天时间，Star数从几百暴涨到了40多K，光是昨天一天就猛涨了30K。\n这绝对是现象级的开源项目啊。\n更离谱的是，据说因为这个项目，Mac Mini的销量都跟着涨了一波。\n要知道一台配置好点的Mac Mini可不便宜，几万块钱的东西，居然被一个开源软件带火了？但实际上这玩意儿使",
    "word_count": 4506,
    "hotness": 1.2
  },
  {
    "title": "打通国内生态，教你把Clawdbot接入飞书",
    "url": "https://mp.weixin.qq.com/s/Et-aRLUEX1nmqXEtUfOPLA",
    "date": "2026-01-27",
    "source": "微信-智语观潮",
    "category": "生态集成",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "import\n{\nClawdbot\n}\nfrom\n'Feishu'\n;\n// 打通国内生态\n\"把Clawdbot接入飞书，无需翻墙，秒速体验AI贾维斯\"\n上一篇教程\n先别急着买Mac mini : 教你免费部署Clawdbot在云端，自己先玩明白\n我们手把手在AWS上免费部署了Clawdbot，那只横空出世的\"AI 助手\"让不少朋友直呼\"未来已来\"。\n但有一个问题一直困扰着国内用户——Clawdbot支持的那么多IM系统，全是国外的，每次对话都得先\"翻个墙\"，实在不够优雅。\n能不能把Clawdbot接到飞书上？我捣鼓了几个小时，有了以下结论。\n答案是：完全可以，而且用的是飞书的\n长连接模式\n，",
    "word_count": 8147,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot最新部署教程，含第三方 Claude API 配置！！",
    "url": "https://mp.weixin.qq.com/s/-fTlKWeJ38UGvuKNjqlSNw",
    "date": "2026-01-27",
    "source": "微信-小目标俱乐部",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "Clawdbot\n：一个在自己设备上运行的个人单用户AI助手，只要电脑、服务器不关机，可以随时通过网页或者WhatsApp、Telegram、Discord等，通过聊天让它帮你干活。\n相信大家最近都看到了 Twitter、公众号、视频号 上面关于\nClawdbot\n的相关言论，但是却不知道如何去尝试和使用这些新的技术和工具。\n今天这篇文章就手把手教大家无痛安装和使用\nClawdbot\n。\n## Clawdbot 安装前置条件：下载 Node.js\n（1）去\nNode.js\n官网下载安装包.（Node官网网站链接：\nhttps://nodejs.org/en/download\n）\n（2）\n确保\n",
    "word_count": 2504,
    "hotness": 1.2
  },
  {
    "title": "3000多的Mac mini被一夜抢空？Clawdbot，给了苹果最不想接的泼天富贵……",
    "url": "https://mp.weixin.qq.com/s/kTtZLfrHAPlbF5fQgEh3bg",
    "date": "2026-01-27",
    "source": "微信-AI深度科技",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "入门科普",
    "summary": "不是？？？？？？\n谁家好人买\nMac mini\n用“囤”的啊？！\n一个两个三四个，五个六个七八个……\n船长在东北买10块钱一份的铝盒饭，都不敢买这满满的一桌子。怕给撑死喽。\n但在外网，Mac mini最近却跟不要钱似的，被大家疯抢。\n甚至，它已经出现了严重的短缺问题。\n呃，就连谷歌大佬Logan Kilpatrick也没忍住跟风，\n“已剁手下单Mac mini。”\n你问为什么会这样子？\n不是苹果在搞什么“0元购”，（苹果自家的销售人员估计也挺懵X的），而是因为——\nClawdbot火了。\nClawdbot火了，Mac mini涨了，苹果的销售人员懵了……\n全网都在聊的Clawdbot，到底是个",
    "word_count": 3109,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot爆火|范式演进：全网首个架构解剖",
    "url": "https://mp.weixin.qq.com/s/ZaXiEYLa6wU5aZ5aid0iiA",
    "date": "2026-01-26",
    "source": "微信-AIGC从0到1",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "导言：在国内被低\n估的\nClawdbot\n2025 年 12 月 30 日，Peter Steinberger 在\n2025 年 12 月 30 日\n发表了一篇详细阐述其工作流的长文，\nClawdbot 经过了一个短暂的“发酵期”，在 2026 年初因其颠覆性的用户体验而迎来了爆发式增长。\n甚至带动了苹果Mac mini的销量。用户们兴奋地展示成果：躺在沙发上发几条Telegram消息，AI就自动修复了网站Bug、优化了服务器成本、甚至写完并发布了一篇技术博客。\n延续之前\n《\nSkills是很火的预制菜，但未来属于专属主厨\n》\n的观点，我认为，是一个更深层次的信号：AI领域的焦点，正\n转向更为",
    "word_count": 5154,
    "hotness": 2.4
  },
  {
    "title": "让Mac mini卖爆，这个开源版贾维斯Clawdbot太强了，附入门教程",
    "url": "https://mp.weixin.qq.com/s/brr-XnVqvOn0ss7dYpK6_A",
    "date": "2026-01-26",
    "source": "微信-AIGC新知",
    "category": "产品认知",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "大家好，我是周一早上又被卷到的绛烨，被卷死了。\nClawdbot又是个啥？\n我一脸懵圈。\n又一个ai编程玩具。\n于是我去刷了一下，\nClawdbot这个项目\n，目前已经\n24k Star\n。\n不只是国内，在外网同样火得离谱，甚至还顺带把\nMac mini\n又炒热了一波。\n有个大兄弟，直接上了40台Mac mini，太土豪了。\n一开始看介绍，你可能会觉得它也没多新鲜：\n能聊天、能执行任务、能接 Telegram / Discord，看起来和一堆 AI 助手差不多。\n但真正上手之后才发现，它的设计思路其实非常反直觉：\n换句话说，它不是那种只有本地化部署的AI，而是一个\n真正能在你电脑里干活的 AI",
    "word_count": 2595,
    "hotness": 1.2
  },
  {
    "title": "全网首曝：Clawdbot用自动化记忆破局“不可能三角”",
    "url": "https://mp.weixin.qq.com/s/T3unIVaBlaawLnnRBaGb3w",
    "date": "2026-01-26",
    "source": "微信-AIGC从0到1",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "引言：记忆——Agent架构的“灵魂”战场\n如果说大模型是AI的“大脑”，那么记忆系统就是其“灵魂”。它决定了AI的个性、连续性以及与我们协作的深度。延续之前的文章的关注点，\nSkills是很火的预制菜，但未来属于专属主厨\nClawdbot爆火|范式演进：全网首个架构解剖\n继续探索“自主上下文工程”，这一篇讨论记忆系统，当前，Clawdbot、OpenWork、Eigent、AionUi展现了三种截然不同的记忆哲学。\n01 三种记忆哲学与技术实现\n1. Clawdbot：记忆作为“可审计的个人资产”\n-核心哲学\n：\n开放与可控优先。坚信用户对记忆应拥有绝对主权和透明度\n。\n-\n技术实现\n：\n*",
    "word_count": 4402,
    "hotness": 2.4
  },
  {
    "title": "从安装到运行：手把手教你用Clawdbot完成第一个智能任务",
    "url": "https://mp.weixin.qq.com/s/cFGkE_iux-UfI5_M0jIItw",
    "date": "2026-01-26",
    "source": "微信-数智转型架构师",
    "category": "安装部署",
    "sub_category": "通用部署",
    "depth": "教程实操",
    "summary": "这两天Clawdbot可谓在AI圈里闹翻天了！\n它到底是什么？\nClawdbot是由\nPeter Steinberger\n（PSPDFKit 创始人）及其团队开发的，它绝不仅仅是对大语言模型的简单封装，它代表了一种全新的计算范式：将分布式智能、本地硬件控制，以及全球主流通信协议（如 WhatsApp、Telegram、iMessage）深度融合，从而构建出一个能够\n7×24 小时持续运行、自主完成复杂任务的数字生命体\n。\n为了尝试一下这个新物种，我也迫不及待地安装起来，看看到底它能干点啥？\n以下就是我为大家写的Windows11环境下的Clawdbot安装教程，在教程最后，我还演示了如何用Cl",
    "word_count": 1947,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot 配置第三方 Claude API：告别官方账号的烦恼",
    "url": "https://mp.weixin.qq.com/s/s7xzFbnaxE_BVZB2vLgvcA",
    "date": "2026-01-26",
    "source": "微信-AI工具进化论",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "最近 Clawdbot 在 Twitter 上火得一塌糊涂。简单说，它是一个跑在你自己电脑上的 AI 助手，可以通过 Telegram、WhatsApp、Discord 等聊天软件跟它对话，让它帮你干活——浏览网页、读写文件、执行脚本、定时任务，什么都能做。\n有人说它是「开源版 Siri，但比 Siri 强一百倍」。Karpathy 都在推上点赞，说明确实有点东西。\n今天折腾了一晚上，终于把 Clawdbot 配上了我的中转 Claude 模型。踩了不少坑，但搞定之后真的爽，不用再操心 Claude 官方账号的问题了。\n为什么要用第三方 API？\nClawdbot 默认用 Anthropic ",
    "word_count": 2359,
    "hotness": 1.2
  },
  {
    "title": "先别急着买Mac mini : 教你免费部署Clawdbot在云端，自己先玩明白",
    "url": "https://mp.weixin.qq.com/s/pOT6Xkzx466DjaoRGpuf7g",
    "date": "2026-01-26",
    "source": "微信-智语观潮",
    "category": "安装部署",
    "sub_category": "macOS本地",
    "depth": "教程实操",
    "summary": "const\nquestion\n=\n\"如果AI能主动帮你处理杂事\"\n;\n// 一个真正的贾维斯，会是什么样？\n\"不是被动等待你提问的聊天机器人，而是会主动给你发消息、帮你处理杂事、甚至自己编写代码扩展能力的AI助手\"\n这两天，一个叫\nClawdbot\n的开源项目在硅谷技术圈炸开了锅。GitHub星标短短几天破万，Discord社区涌入数千人，有人说，这是自ChatGPT发布以来，再一次让人真切感受到\"未来已来\"的震撼。\n今天，我们就来聊聊这只横空出世的\"龙虾AI\"——它到底是个什么东西，为什么这么多人对它着迷，以及最关键的问题：我们普通用户能怎么玩儿，如何部署？\n★\n文末附\n手把手AWS免费部署",
    "word_count": 6011,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot 配置第三方 Claude API：告别官方账号的烦恼",
    "url": "https://mp.weixin.qq.com/s/s7xzFbnaxE_BVZB2vLgvcA",
    "date": "2026-01-26",
    "source": "微信-AI工具进化论",
    "category": "配置与技巧",
    "sub_category": "",
    "depth": "教程实操",
    "summary": "最近 Clawdbot 在 Twitter 上火得一塌糊涂。简单说，它是一个跑在你自己电脑上的 AI 助手，可以通过 Telegram、WhatsApp、Discord 等聊天软件跟它对话，让它帮你干活——浏览网页、读写文件、执行脚本、定时任务，什么都能做。\n有人说它是「开源版 Siri，但比 Siri 强一百倍」。Karpathy 都在推上点赞，说明确实有点东西。\n今天折腾了一晚上，终于把 Clawdbot 配上了我的中转 Claude 模型。踩了不少坑，但搞定之后真的爽，不用再操心 Claude 官方账号的问题了。\n为什么要用第三方 API？\nClawdbot 默认用 Anthropic ",
    "word_count": 2359,
    "hotness": 1.2
  },
  {
    "title": "Clawdbot 的真正创新是网关：一篇了解架构、权限和风险",
    "url": "https://mp.weixin.qq.com/s/FVm1z1XE_q9dEp8aPI2TIw",
    "date": "2026-01-26",
    "source": "微信-架构师",
    "category": "产品认知",
    "sub_category": "",
    "depth": "深度分析",
    "summary": "架构师（JiaGouX）\n我们都是架构师！\n架构未来，你来不来？\n先用 30 秒把它讲明白\n如果你这两天没刷到 Clawdbot，很正常。\n一句话解释：\nClawdbot 是一个开源的个人 AI 助手\n。你把它跑在自己的电脑或服务器上，然后用 WhatsApp、Telegram 这类即时通信软件给它发消息，它就能在那台机器上替你干活。\n它能干的事，大致是这几类：\n• 帮你回邮件、安排会议、抓数据\n• 管理文件、运行脚本、做自动化\n• 甚至写代码，给自己扩展新功能\n它背后的理念也很直白：\n•\n去云端中心化\n：AI 跑在你控制的设备上，你用聊天软件遥控它干活\n•\n开放与自定义\n：用户可编程，可扩展",
    "word_count": 4439,
    "hotness": 1.2
  },
  {
    "title": "迎接数字生命：一文看懂忽然爆火的Clawdbot 本地主动智能体",
    "url": "https://mp.weixin.qq.com/s/e9EY4sGGR587iYPgUYT87Q",
    "date": "2026-01-26",
    "source": "微信-Web3天空之城",
    "category": "产品认知",
    "sub_category": "",
    "depth": "入门科普",
    "summary": "Web3天空之城|城主\n前言\n2026年开篇, AI的演进正经历从“被动式对话界面”向\n主动式执行代理（Agentic Engineering）\n的历史性飞跃。\n如果说 2023 年是 Chat UI 的元年，让我们习惯了和 AI 唠嗑；那么到了 2026 年初，风向已经彻底变了。这两天一个名为\nClawdbot\n的项目，在硅谷和全球极客圈引发了一场核爆级的震动。\n它由\nPeter Steinberger\n（PSPDFKit 创始人，推特 ID @steipete）及其团队开发。它不仅仅是一个大语言模型（LLM）的封装器，它代表了一种全新的计算范式：\n将分布式智能、本地硬件控制与全球主流通信协",
    "word_count": 6491,
    "hotness": 1.2
  }
];
